### ISSUE TITLE
[FR] Total value of everything in storage

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#2507] opened 2022-01-06 14:26 UTC
**Problem**
It's the beginning of a new year again and we are cleaning up our taxes. For this we need to know an estimate of how much value we currently have in storage.

**Suggested solution**
It would be cool if selected roles can see the total value of the supply in the System Information popup.

**Describe alternatives you've considered**
Currently I have written a little script that pulls every stock item from the inventree instance and sum up their prices.

**Examples of other systems**
I don't think it's an uncommon feature in these kind of systems however I wouldn't know of a example program at the moment...

**Do you want to develop this?**
I think I can do it, but I need help with making it efficient as to not overload the server too much.

**Comment by matmair** [comment] 2022-01-06 22:34
@Guusggg this seems like a great use case for a report as it is not needed too often.

**Comment by Guusggg** [comment] 2022-01-07 08:44
@matmair Oh right, a report! Totally forgot about them. It might even be possible to do it today, with all the variables being exposed to that API.

**Comment by matmair** [comment] 2022-01-07 10:40
@guusggg no problem, it is not documented a lot so I tend to also forget about it. I hope to build an easy mechanism to share and customize report templates this year. Something like plugins (maybe using them) and a WYSIWYG - type editor.

**Comment by SchrodingersGat** [comment] 2022-01-07 11:09
@matmair I look forward to seeing what you can come up with :) we use reports very extensively at work, but it is definitely poorly documented and under appreciated!

**Comment by matmair** [comment] 2022-01-08 17:38
@Guusggg can we close this for now as it most likely a custom report or would you be willing to submit it upstream?
@SchrodingersGat this is on the looooong-term TODO-list 👼

**Comment by SchrodingersGat** [comment] 2022-01-09 09:25
I'll leave it open for now, we can think about it for a bit

**Comment by Guusggg** [comment] 2022-01-09 12:41
@matmair I don't mind closing it, do it as you guys please ^^. I can submit the script I wrote upstream but it's nothing special...

```python
from inventree.api import InvenTreeAPI
from inventree.stock import StockLocation, StockItem

api = InvenTreeAPI(SERVER_ADDRESS, username=MY_USERNAME, password=MY_PASSWORD)
items = StockItem.list(api)

items_without_price = 0
total = 0
for item in items:
    item_price = 0

    if not item.in_stock:
        #print(f"{part.name} is not in stock! Quantity={item.quantity}, Pk={item.pk}")
        continue 

    if item.purchase_price:
        item_price = float(item.quantity) * float(item.purchase_price)
    else:
        part = item.getPart()

        print(f"{part.name} has no pricing! Quantity={item.quantity}, Pk={item.pk}")
        items_without_price += 1

    #print(f"Part {item.quantity} bought for {item.purchase_price}")
    
    total += item_price

print(f"{len(items)} items at {total} value.")
print(f"{items_without_price} items without pricing")
```
I think I can easily port this to the web function tho so I'll try that and submit it upstream.

Thanks a lot guys!

**Comment by SchrodingersGat** [comment] 2023-01-08 21:12
Closing as duplicate of https://github.com/inventree/InvenTree/issues/2191

**Closed by SchrodingersGat** 2023-01-08 21:12 UTC
Labels: enhancement, report, pricing
