### ISSUE TITLE
AttributeError when creating purchase order

### ISSUE THREAD

**Issue by jatNIM** [inventree/InvenTree#6080] opened 2023-12-13 10:46 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When creating a purchase order after clicking "submit" an error pops up. After checking the "Admin" panel the info on the error is 'str' object has not attribute 'removesuffix'. 

Restarted the server already and no change.

I cannot reproduce this error in the demo version

### Steps to Reproduce

1. Go to "Purchase orders"
2. Click on create new Purchase order
3. Fill in the complete form
4. Click on "submit"
5. Error screen pops up
6. Returning to website
7. Purchase order is created
8. Cannot edit of access the created purchase order

### Expected behaviour

I expect to save the new purchase order, to see the details of the purchase order, and to change the status/close the purchase order.

### Deployment Method

- [ ] Docker
- [x] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.8
Django Version: 3.2.19
Commit Hash: a7487ff8
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-6.2.16-3-pve-x86_64-with-glibc2.29
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
response = response.render()

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 105, in render
self.content = self.rendered_content

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
return template.render(context, self._request)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 170, in render
return self._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/library.py", line 192, in render
output = self.func(*resolved_args, **resolved_kwargs)

File "/opt/inventree/InvenTree/generic/states/tags.py", line 14, in status_label
state = {cls.tag(): cls for cls in inheritors(StatusCode)}.get(typ, None)

File "/opt/inventree/InvenTree/generic/states/tags.py", line 14, in <dictcomp>
state = {cls.tag(): cls for cls in inheritors(StatusCode)}.get(typ, None)

File "/opt/inventree/InvenTree/generic/states/states.py", line 108, in tag
ref_name = cls.__name__.removesuffix('Status')

AttributeError: 'str' object has no attribute 'removesuffix'
```

**Comment by SchrodingersGat** [comment] 2023-12-13 11:10
@jatNIM your python version needs to be [3.9 or greater](https://docs.inventree.org/en/stable/start/intro/#python-requirements) - please update!

Closing this issue out, as it is a duplicate of [multiple existing issues](https://github.com/inventree/InvenTree/pull/6081)

**Closed** 2023-12-13 11:10 UTC
Labels: duplicate, question, setup
