### ISSUE TITLE
Formatting of emails is shifted

### ISSUE THREAD

**Issue by method1020** [inventree/InvenTree#4318] opened 2023-02-07 15:13 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The lower portion of the email notification template is wider than the top section. 

I have not tested this with shorter Purchase Order or other type of document identifiers.

### Steps to Reproduce

1. Receive notification email.
2. Notice the lower table portion is wider than the top portion.
3. This is viewed in Microsoft Outlook (365)

![Screenshot 2023-02-07 100756](https://user-images.githubusercontent.com/3278824/217284246-48bda637-cf7b-4a31-bf63-9ce00eeca984.jpg)

### Expected behaviour

Expected the table to stack correctly.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.2
Django Version: 3.2.16
Commit Hash: 236ca36
Commit Date: 2023-01-04
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: []

**Comment by matmair** [comment] 2023-02-07 15:32
@method1020 can you reproduce this on the demo instance?

**Comment by matmair** [comment] 2023-02-07 19:35
This seems to come down to the HTML in the report. So something that is probably a bit of tinkering but does not require a lot of architectural knowledge. It is probably in `InvenTree/report/templates/report/inventree_po_report.html` or `InvenTree/report/templates/report/inventree_report_base.html`

**Comment by simonkuehling** [comment] 2023-02-07 20:03
The base template would be https://github.com/inventree/InvenTree/blob/master/InvenTree/templates/email/email.html I think - that's where that table seems to be defined. I don't see an obvious formatting problem there at the moment - but maybe @method1020 could post the full html source code of that email here?

**Comment by method1020** [comment] 2023-02-09 00:52
It seems to be a formatting issue with Outlook 365 (Desktop) version.

If I view the email in Outlook online, it renders correctly. If I dump the html into a file and open it in Chrome and Firefox, it renders correctly.

![image](https://user-images.githubusercontent.com/3278824/217686266-f5b6637e-a24c-4423-aecc-db378c188abf.png)

**Comment by matmair** [comment] 2023-02-09 22:50
So can we close this @method1020 ? Seems to be a problem with Outlook rendering.

In my experience, HTML E-Mails are hard because some vendors rendering engines do not adhere to standards / interpret them differently.

**Comment by matmair** [comment] 2023-02-09 22:51
Also thank you for checking/ your input @simonkuehling!

**Comment by matmair** [comment] 2023-02-13 06:58
Closing due to lack of response. Please feel free to reopen if the problem reappears.

**Closed by matmair** 2023-02-13 06:58 UTC
Labels: question, report

**Comment by method1020** [comment] 2023-02-13 13:19
Yes. It is only Outlook desktop having the rendering issue.

In my industry Outlook desktop is pretty common. I'll see if I can get one of my dev friends to help fix it.

**Comment by matmair** [comment] 2023-02-13 18:03
Desktop Outlook is hard to target as there are at least 3 versions out there. At my company, I have Office 2019 E, Office 365 and Office 365 (on Win 11) with differently behaving renderers. I decided to only target OWA/Office Online as that is the only somewhat performant and stable Outlook anymore.
