### ISSUE TITLE
[BUG] Crash when uploading image for a part

### ISSUE THREAD

**Issue by lukh** [inventree/InvenTree#2884] opened 2022-04-27 07:30 UTC
**Describe the bug**
When trying to upload an image for the part, either via the WebInterface, either via the Python API, 
got a server crash, with the same traceback

**Steps to Reproduce**

Steps to reproduce the behavior: (WebUI)
1. go to a part,
2. on the thunbnail, click on upload image, 
3. select a file
4. upload

OR (python)
my_part.uploadFile(path_to_file)

**Expected behavior**
`sb-inventree-server  | Traceback (most recent call last):
sb-inventree-server  |   File "/usr/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
sb-inventree-server  |     self.handle_request(listener, req, client, addr)
sb-inventree-server  |   File "/usr/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
sb-inventree-server  |     respiter = self.wsgi(environ, resp.start_response)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
sb-inventree-server  |     response = self.get_response(request)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
sb-inventree-server  |     response = self._middleware_chain(request)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
sb-inventree-server  |     response = response_for_exception(request, exc)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
sb-inventree-server  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 153, in handle_uncaught_exception
sb-inventree-server  |     return callback(request)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
sb-inventree-server  |     response = view_func(request, *args, **kwargs)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/views/defaults.py", line 97, in server_error
sb-inventree-server  |     return HttpResponseServerError(template.render())
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
sb-inventree-server  |     return self.template.render(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
sb-inventree-server  |     return self._render(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
sb-inventree-server  |     return self.nodelist.render(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
sb-inventree-server  |     bit = node.render_annotated(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
sb-inventree-server  |     return self.render(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
sb-inventree-server  |     return compiled_parent._render(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
sb-inventree-server  |     return self.nodelist.render(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
sb-inventree-server  |     bit = node.render_annotated(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
sb-inventree-server  |     return self.render(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
sb-inventree-server  |     return template.render(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 172, in render
sb-inventree-server  |     return self._render(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
sb-inventree-server  |     return self.nodelist.render(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
sb-inventree-server  |     bit = node.render_annotated(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
sb-inventree-server  |     return self.render(context)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/library.py", line 192, in render
sb-inventree-server  |     output = self.func(*resolved_args, **resolved_kwargs)
sb-inventree-server  |   File "/home/inventree/InvenTree/part/templatetags/inventree_extras.py", line 258, in settings_value
sb-inventree-server  |     return InvenTreeUserSetting.get_setting(key, user=kwargs['user'])
sb-inventree-server  |   File "/home/inventree/InvenTree/common/models.py", line 299, in get_setting
sb-inventree-server  |     setting = cls.get_setting_object(key, **kwargs)
sb-inventree-server  |   File "/home/inventree/InvenTree/common/models.py", line 1241, in get_setting_object
sb-inventree-server  |     return super().get_setting_object(key, user=user)
sb-inventree-server  |   File "/home/inventree/InvenTree/common/models.py", line 249, in get_setting_object
sb-inventree-server  |     settings = settings.filter(user=user)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 941, in filter
sb-inventree-server  |     return self._filter_or_exclude(False, args, kwargs)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
sb-inventree-server  |     clone._filter_or_exclude_inplace(negate, args, kwargs)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
sb-inventree-server  |     self._query.add_q(Q(*args, **kwargs))
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1393, in add_q
sb-inventree-server  |     clause, _ = self._add_q(q_object, self.used_aliases)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
sb-inventree-server  |     child_clause, needed_inner = self.build_filter(
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
sb-inventree-server  |     condition = self.build_lookup(lookups, col, value)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
sb-inventree-server  |     lookup = lookup_class(lhs, rhs)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/lookups.py", line 25, in __init__
sb-inventree-server  |     self.rhs = self.get_prep_lookup()
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 117, in get_prep_lookup
sb-inventree-server  |     self.rhs = target_field.get_prep_value(self.rhs)
sb-inventree-server  |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
sb-inventree-server  |     raise e.__class__(
sb-inventree-server  | ValueError: Field 'id' expected a number but got ''.
`

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
0.6.2

**Comment by SchrodingersGat** [comment] 2022-04-27 07:46
@lukh is this the complete full traceback? Can you please provide the entire thing?

**Comment by lukh** [comment] 2022-04-28 16:05
[logs.txt](https://github.com/inventree/InvenTree/files/8584415/logs.txt)
Here, from docker-compose logs !

It looks like a recursive exception or somethin like that ?
(by the way, inventree is amazing !!)

**Comment by SchrodingersGat** [comment] 2022-04-30 06:58
> (by the way, inventree is amazing !!)

Thanks @lukh glad you like it!

The key part of the error logs is the last line I've clipped here:

![image](https://user-images.githubusercontent.com/10080325/166095427-210a1e6a-bfe7-43c3-a884-4c11613df2fa.png)

It appears that the server application does not have permission to write to the "media" directory. This is the location where uploaded files (e.g. part images) are stored. 

Is this the first time you have tried to upload an image for a part? As you are running in docker, it is probably the case that you have not set up a volume for the docker container to write to?

Can you share any of your docker-compose setup? And have you been able to upload any other files (attachments, etc)?

**Comment by lukh** [comment] 2022-04-30 08:37
Thanks for the help !
It is the first time for the images, but i was able to upload attachment

**Comment by lukh** [comment] 2022-04-30 08:54
Okayyy..
It looks like I did forget to mention something...
I have two docker compose setups... one for prod and one for "test", ie that I use to run small scripts on it..
the prod version works just fine.

The other one... I used a copy of the data folder from the prod one. It doesnt work, even with attachment...
So this lead me to an off topic question... How do I backup my data ?
It looks like 'sudo zip data' doesn't allow to recreate another instance of the docker setup then ?

Thanks

**Comment by matmair** [comment] 2022-04-30 11:46
@lukh as this is def not a bug I am closing this issue. If you have questions about backup (saving and restoring a specific instance) please read the [following docs](https://inventree.readthedocs.io/en/latest/start/migrate/) and feel free to open a discussion if questions arise.

**Closed by matmair** 2022-04-30 11:46 UTC
Labels: question, docker, setup
