### ISSUE TITLE
after update to .11.x can no longer set stock status

### ISSUE THREAD

**Issue by gablesm** [inventree/InvenTree#4948] opened 2023-06-01 21:37 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

selecting Stock, and then any stock item, previous instances allowed us to select the stock item, choose stock options and then set stock status.  

the interesting detail is that the list appears to show but no text is visible.  you can scroll down the list and blindly select a value and it will update the DB.  

on the stock status page it actually shows the proper stock status.

thanks for the help!

### Steps to Reproduce

1 - Go to Stock, stock items, (select any item)
2 - select stock options, then scroll down to 'Change stock status'
3 - new window appears but the only option that is visible is '---------'.  if you scroll up or down, you will see other the cursor highlight change and you can accept it.  it will update the DB and the stock status value but no text available within window so you must guess as to the selection.
![image](https://github.com/inventree/InvenTree/assets/1297480/81d9bd6a-62c0-4dee-b794-4765276a569f)

### Expected behaviour

we would expect to see the standard stock status items like OK or DAMAGED

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.2
Django Version: 3.2.18

Database: postgresql
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

**Comment by matmair** [comment] 2023-06-01 21:50
Have you checked https://docs.inventree.org/en/latest/faq/#feature-x-does-not-work-after-update and restarted the server after the update?

**Comment by gablesm** [comment] 2023-06-01 21:57
Yes.  We’ve been running inventree for about a year with no issues on
upgrades.

**Comment by matmair** [comment] 2023-06-02 05:51
@gablesm can you provide screenshots of every step or try to reproduce on demo.inventree.org? I have problems reproducing with the provided instructions (demo is on master, not 0.11.2).

**Comment by walkermc20** [comment] 2023-06-16 15:54
Just checked the demo server and the "Change Stock Status" is not included on the 0.12.0 dev branch?  Does not appear to be an option.  
![Screenshot 2023-06-16 115344](https://github.com/inventree/InvenTree/assets/34684351/44149e4f-51d5-4ffa-9375-da9a9bfc9dcb)

**Comment by SchrodingersGat** [comment] 2023-06-16 22:20
Looks like a regression - I'll ensure it is fixed by next release.

**Closed** 2023-06-17 21:40 UTC
Labels: bug, question, api
