### ISSUE TITLE
Input filter does not work in Create Build Order modal

### ISSUE THREAD

**Issue by afkiwers** [inventree/InvenTree#2267] opened 2021-11-08 01:02 UTC
**Describe the bug**
When adding a build order and selecting a user for issued by and resposnisble, the filter does not work. When entering a name the list simply re-orders in a somewhat unexpected way.

Also, the names are differently formatted in each select field

**Steps to Reproduce**

Open create a build order strating from an arbitarty assembly

**Expected behavior**
Remove names which don't partially match the input.

**Screenshots**
![image](https://user-images.githubusercontent.com/42826581/140669135-f647b7e6-aed4-479b-80d7-39b18ffb3920.png)
![image](https://user-images.githubusercontent.com/42826581/140669272-5cb83850-643b-4582-a98d-412960c2127d.png)

**Version Information**
![image](https://user-images.githubusercontent.com/42826581/140669357-81ab0463-1ebc-49ce-88cb-bc2890043caa.png)

**Comment by SchrodingersGat** [comment] 2021-11-08 02:13
Duplicate of https://github.com/inventree/InvenTree/issues/2022

**Closed by SchrodingersGat** 2021-11-08 02:13 UTC
Labels: bug, question
