### ISSUE TITLE
[bug] pricing autofill in purchase orders

### ISSUE THREAD

**Issue by T0jan** [inventree/InvenTree#4902] opened 2023-05-26 09:37 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

hi again,

I found that between `0.11.0 dev` and `0.12.0 dev` a for me quite useful function was removed and I wanted to check if this is intended: in `0.11.0 dev` editing a line item of a purchase order automatically changed the price to the latest information available in the `Supplier Part Pricing` of the assigned `Supplier Part` of this line item. So e.g. if a part had a price of 10$ per item at first, the price was updated to 9.50$ while the purchase order was prepared, then editing this specific line item would change the purchase price to 9.5$ as well. in `0.12.0 dev` the price now never gets updated, is this intended?

If the function is intended to come back I also would suggest, that some kind of autofill on creation function is added. Adding a line item to a purchase order should automatically set the fitting price based on the available pricing information to have at least a rough estimation of the total price initially.

### Steps to Reproduce

1. add a line item to a purchase order
2. make sure the item has a `Supplier Part Pricing` entry
3. edit the line item in the purchase order
on `0.11.0 dev`: the price is autofilled
on  `0.12.0 dev`: the price remains empty

### Expected behaviour

The price should be autofilled in  `0.12.0 dev` as well. If the function comes back an autofill on creation of the line item, not just on editing would be great.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0 dev
Django Version: 3.2.18
Commit Hash: 1ba51e51c
Commit Date: 2023-03-14
Database: postgresql
Debug-Mode: True
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'Label Printer', 'slug': 'samplelabel', 'version': '0.2'}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.6.0'}]

**VS**

# Version Information:
InvenTree-Version: 0.12.0 dev
Django Version: 3.2.18

Database: postgresql
Debug-Mode: True
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

**Comment by SchrodingersGat** [comment] 2023-05-26 10:46
This was not a planned regression, I'll have to look into the behaviour. 

In terms of moving forward I'd like the user to be able to have controls over the process. The line item price shouldn't update without specific user intervention. Maybe a "refresh" button in the form?

I think auto calculation is good when the line item is first calculated..

There are a lot of other outstanding issues which have my attention currently. Do you want to take a look at this?

**Comment by T0jan** [comment] 2023-05-26 11:07
@SchrodingersGat I can't commit to working on it as I don't know if I find time to work on this. If I do I will come back here and let you know.

**Comment by SchrodingersGat** [comment] 2023-05-26 11:10
Fair enough!

**Comment by SchrodingersGat** [comment] 2023-10-17 13:50
Removing this from the next release as it likely should be implemented in the new react UI

**Comment by chille** [comment] 2024-01-19 01:37
I have the same problem when working working with Purchase Orders. I'm currently trying to migrate away from LibreOffice Spreadsheets, but can't because the price in the Purchase Order is unreliable because it is hardcoded into each Line Item and not pulled from Supplier Part Pricing.

### I suggest the following solution

Add a configuration to a Purchase Order where the user can select between two different options:

1) Use Supplier Part Pricing (I suggest that this will be the default option in the future)
2) Specifiy a price on each Line Item

When the first option is selected the following things will happen:

1) The UI will disable the "Purchase Price" field when editing a Line Item and also tell the user why.
2) The backend will check if the Purchase Order is configured to use Supplier Part Pricing and if so do the following:
	* Include the correct purchase_price in /api/order/po-line
	* Report an error if changes are made to the purchase_price field in /api/order/po-line

When changing configuration from "Supplier Part Pricing" to "Specifiy a price on each Line Item" then the current Supplier Part Pricing should be imported into each Line Item.

When "Issue Order" is pressed there should also be an option to change the pricing configuration and import and lock all prices.

When "Specifiy a price on each Line Item" is used it might be a good idea to have an "Import current prices" button.

It could maybe be a good idea to let the API always include both the Line Item price and the Supplier Part Pricing and let the UI show a warning if there is a discrepancy between the two prices.

**Comment by SchrodingersGat** [comment] 2024-04-22 03:19
@Mimosa-oceanis thanks for reporting - looks like there was a bug here - fix incoming in https://github.com/inventree/InvenTree/pull/7075

**Comment by matmair** [comment] 2024-04-23 05:49
@SchrodingersGat can we close this now that #7075 is released?

**Comment by wolflu05** [comment] 2024-04-23 05:57
Also related to #6483

**Comment by SchrodingersGat** [comment] 2024-04-23 06:12
Yes, I believe this can be closed out now.

**Closed by SchrodingersGat** 2024-04-23 06:12 UTC
Labels: bug, question, order, user interface, pricing, Platform UI
