### ISSUE TITLE
Feature or Bug. Items allocation.

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2390] opened 2021-11-30 13:43 UTC
Why we can allocate more quantity than line items has?

**Comment by lookme2** [comment] 2021-11-30 14:21
I am seeing this also.  I reported it but was asked for some screen shots.  I'm not in my office so cant do that yet.  Seems to only happen when you use the "Auto Allocate" button.

**Comment by SchrodingersGat** [comment] 2021-11-30 21:12
Duplicate of https://github.com/inventree/InvenTree/issues/2380

**Closed by SchrodingersGat** 2021-11-30 21:12 UTC
