### ISSUE TITLE
[FR] Components availability and stock for suppliers

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#2569] opened 2022-01-24 19:22 UTC
**Problem**

I managed to import all the BOM's and components from the excel I was using previously into the Inventree and I created a script to pull prices from popular components distributors every day and upload them to InvenTree. The issue I am having is I don't see an option to attach stock availability. now when creating purchasing order I know the approximate price based on the quantity but I don't know if those components are available at the distributor (supplier) website.

**Suggested solution**

Add a column or option to see component availability for suppliers and also see how much quantity of the components they currently hold in stock, those can be inserted manually.

**Describe alternatives you've considered**

Before purchasing entering to each supplier link and see if the component is available or not. this is a lot of manual work and Id like to see everything through InvenTree before adding a component for purchase from a certain supplier.

**Comment by matmair** [comment] 2022-01-24 20:39
Hi there @Zontex thanks for the FR!
Do you want to develop this?

As for the possible architecture: I would add an extra model that links a supplier-part to a quantity, timestamp and optional TTL. Then there should be API-endpoints that give access to these values - so that the UI / an app can fetch the info async. There should be public functions to add information in an efficient way so it can be used for a mixin to enable plugins to add that information. This would be prime material for a few plugins (Digikey, Octo, LSCS, etc).
This should be a 0.7.0 milestone at least as it should be unit and e2e tested and profiled to not introduce massive latency problems.

**Comment by matmair** [comment] 2022-01-24 20:43
@SchrodingersGat what importance/interest would you assign to this?

**Comment by Zontex** [comment] 2022-01-25 09:09
> Hi there @Zontex thanks for the FR! Do you want to develop this?
> 
> As for the possible architecture: I would add an extra model that links a supplier-part to a quantity, timestamp and optional TTL. Then there should be API-endpoints that give access to these values - so that the UI / an app can fetch the info async. There should be public functions to add information in an efficient way so it can be used for a mixin to enable plugins to add that information. This would be prime material for a few plugins (Digikey, Octo, LSCS, etc). This should be a 0.7.0 milestone at least as it should be unit and e2e tested and profiled to not introduce massive latency problems.

I think I need some more time to get around the code to be able to contribute, will check it out and see what I can do.
Currently, my python scripts update through "http://%s/api/company/price-break" API, which means I need to send a few (5-6 requests) for each product in order to update the pricing, there is no batch updating with a single JSON file which will be more efficient. Or, perhaps, uploading a text file sending a big JSON for all the products could be a good idea as well. 

Another bug I found is if you have a pending purchasing order and you update all the pricing for all the components for the supplier, the pricing order will not update. you need to delete all the items and manually add them again in order to get the latest price. will be nice to have a button says "get latest pricing" or automatically fetch the latest pricing.

**Comment by matmair** [comment] 2022-01-25 09:49
> I think I need some more time to get around the code to be able to contribute, will check it out and see what I can do. 

Sure, let us / me know if you have questions. We also have discussions enabled.

> Currently, my python scripts update through "http://%s/api/company/price-break" API, which means I need to send a few (5-6 requests) for each product in order to update the pricing

That seems to be a bit much. Maybe cache the parts list. It should be more like 1. something per part.

> there is no batch updating with a single JSON file which will be more efficient. Or, perhaps, uploading a text file sending a big JSON for all the products could be a good idea as well.

Technically possible to implement but could be a lot of work for a limited use case. A function like that needs to be bulletproof regarding testing and performance implications. If you need to make a lot of changes on a regular basis maybe use [plugins](https://inventree.readthedocs.io/en/latest/extend/plugins/).

> Another bug I found is if you have a pending purchasing order and you update all the pricing for all the components for the supplier, the pricing order will not update. 

Not a bug, feature :-), auto changing set prices (you can also add prices by hand in orders) could cause problems

> you need to delete all the items and manually add them again in order to get the latest price. will be nice to have a button says "get latest pricing" or automatically fetch the latest pricing.

That could be a FR.

**Comment by matmair** [comment] 2022-01-25 19:29
@eeintech I think we are talking about different things. As I understood OP he wants to save the availability of parts, not the price. So pricebreaks would be the wrong place. Also pricebreaks and availability should not be connected as they are not either in the real world. Would you read OPs request in another way?

**Comment by eeintech** [comment] 2022-01-26 18:29
@matmair Right I read it diagonally :confused:

**Comment by SchrodingersGat** [comment] 2022-01-27 02:08
An "availability" field could be added to the SupplierPart model, as well as a "availability_last_updated" field.

However, (especially given the current state of electronics supply) the reliability of the data stored here would be tenuous at best.

Maybe this would be best implemented as a plugin, which creates a separate database table that links to a SupplierPart model?

**Comment by Zontex** [comment] 2022-01-27 11:29
> An "availability" field could be added to the SupplierPart model, as well as a "availability_last_updated" field.
> 
> However, (especially given the current state of electronics supply) the reliability of the data stored here would be tenuous at best.
> 
> Maybe this would be best implemented as a plugin, which creates a separate database table that links to a SupplierPart model?

My script currently updates the prices of a little over 200 parts 4 times per day (every 6 hours) and it works great, I figured out prices don't change that much, only stock but it works out pretty well. the issue i can't see the stock unless I click the item before purchasing, when doing check-out on the supplier order will be nice to be able to see the available quantity and a flag if the available quantity is low or 0.

I think adding it to SupplierPart together with a timestamp would be absolutely worth it.

**Comment by matmair** [comment] 2022-01-27 19:12
> Maybe this would be best implemented as a plugin, which creates a separate database table that links to a SupplierPart model?

I think it would make sense as a core module - but could be a plugin as a test. It should be its own model in my mind as availability and price often are not coupled.

My users do not really need this so my interest in deving this is low. @Zontex  maybe try the plugin route and ping us if you run into issues.

**Comment by SchrodingersGat** [comment] 2022-01-27 23:29
Having a second chance to think about this, I think having this as a core feature does make sense. Auto-updates of this information would have to be handled by plugins - that is far outside the core scope of InvenTree.

**Comment by Zontex** [comment] 2022-01-28 00:32
Exactly my thought.
Each supplier / factory can have their own plugin to integrate and update
the variables but at least have the field of price and last updated in the
core, what do you think?

**Comment by SchrodingersGat** [comment] 2022-01-28 00:39
Agreed. I've added this to the milestones for next major release :)

**Comment by matmair** [comment] 2022-01-28 22:58
@SchrodingersGat if possible I would find it very useful to have this as a separate model so that there can be time to live / valid attached to it and statistical information can be gathered from the history of stock availability.

**Comment by Zontex** [comment] 2022-01-29 15:49
I've been working with the official authentication API to insert price breaks and I found a great difficulty to update existing price breaks. When you insert a price break for the first time you only need part id which is easy because you take all the supplier parts which has part_id as well and then you literate through them, get SKU, get real-time price and quantity from supplier and insert. 

When you update, you need the unique PK that is given when the price break (for that particular price break) when it was inserted, there are about 4-6 price breaks for each component, a supplier might lower the price break or change the amount of the price breaks which will make it very difficult to update exactly the right price break.

Till now, I can't figure out how to update the price break like that, what I do, is I delete all supplier price break (one by one because there isn't API to delete them all) and then re-insert. am I doing it wrong?

**Comment by SchrodingersGat** [comment] 2022-01-30 09:33
@Zontex you should definitely be able to update price breaks via the API:

https://github.com/inventree/InvenTree/blob/916216acaad4acb8cc660330318c89c156619496/InvenTree/company/api.py#L382

When you attempt to update (rather than delete) do you get an error message?

**Comment by Zontex** [comment] 2022-01-31 03:30
> @Zontex you should definitely be able to update price breaks via the API:
> 
> https://github.com/inventree/InvenTree/blob/916216acaad4acb8cc660330318c89c156619496/InvenTree/company/api.py#L382
> 
> When you attempt to update (rather than delete) do you get an error message?

to update the pricing need the specific breakdown PK ID (each product has about 4 breakdowns which means 4PKs) but I'm wondering if it's possible to add API to update breakdown pricing based on part id number and if it already exists (the same field with a different value or same value) it will update it, there is no way for me to know which break-down I should update unless I save them when I first insert them into the database

**Comment by SchrodingersGat** [comment] 2022-01-31 10:09
You do need the PK  value to update a SupplierPartPriceBreak instance, just the same as any other object in the database.

**Closed** 2022-06-08 11:49 UTC
Labels: enhancement, order, part, user interface, plugin, api
