### ISSUE TITLE
Update .10

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#702] opened 2020-04-06 17:55 UTC
I updated to .10 and now the thumb nail pics will not show in the parts browser.

**Comment by SchrodingersGat** [comment] 2020-04-06 21:42
Did you run `make update`?

Can you please try the following:

1. In the root inventree directory, run `make static`
2. Do a forced refresh (Ctrl + Shift + R)

**Comment by SchrodingersGat** [comment] 2020-04-06 21:47
Interesting. Can you please navigate to where the media files are stored (e.g. uploaded Part images) and check if there are thumbnail images for each image:

![image](https://user-images.githubusercontent.com/10080325/78608307-0578e480-78a4-11ea-86da-dfd112197e7e.png)

There should be a duplicate of each image with ".thumnail." at the end.

**Comment by SchrodingersGat** [comment] 2020-04-07 04:39
Please check to see if the latest update fixes the issue for you.

**Closed** 2020-04-07 04:38 UTC

**Comment by lookme2** [comment] 2020-04-07 15:15
I did not have the thumbnail files but the update did fix it.  Thanks!
