### ISSUE TITLE
[BUG] `templates/js/dynamic/settings.js` is empty and raises JavaScript errors

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#1983] opened 2021-08-20 09:03 UTC
Hi,

Today while updating to the latest master branch I encountered the problem that `settings.js` is bugged:
```javascript
// InvenTree settings
var user_settings = {    
    : ,    
    : ,    
    : ,
    // ... Omitted for brevity    
};

var global_settings = {    
    : ,    
    : ,
    : ,
    // ... Omitted for brevity
};
```
I'm not sure what to do. I screwed around with the Django template language and it seems that there is settings located in the dictionary USER_SETTINGS but its not what the template expects...

Running `{% debug USER_SETTINGS %}` gives me:
```python
{'GLOBAL_SETTINGS': {'BARCODE_ENABLE': True,
                     'BUILDORDER_REFERENCE_PREFIX': 'BO',
                     'BUILDORDER_REFERENCE_REGEX': '',
                     'INVENTREE_BASE_URL': '',
                     'INVENTREE_COMPANY_NAME': 'Pritec Automation',
                     'INVENTREE_DEFAULT_CURRENCY': 'EUR',
                     'INVENTREE_DOWNLOAD_FROM_URL': False,
                     'INVENTREE_INSTANCE': 'InvenTree server',
                     'INVENTREE_INSTANCE_TITLE': False,
                     'INVENTREE_LATEST_VERSION': '',
                     'PART_ALLOW_DUPLICATE_IPN': True,
                     'PART_ALLOW_EDIT_IPN': True,
                     'PART_ASSEMBLY': False,
                     'PART_BOM_USE_INTERNAL_PRICE': False,
                     'PART_CATEGORY_PARAMETERS': True,
                     'PART_COMPONENT': True,
                     'PART_COPY_BOM': True,
                     'PART_COPY_PARAMETERS': True,
                     'PART_COPY_TESTS': True,
                     'PART_CREATE_INITIAL': False,
                     'PART_INTERNAL_PRICE': False,
                     'PART_IPN_REGEX': '',
                     'PART_PURCHASEABLE': False,
                     'PART_SALABLE': False,
                     'PART_SHOW_IMPORT': False,
                     'PART_SHOW_PRICE_IN_FORMS': True,
                     'PART_SHOW_QUANTITY_IN_FORMS': True,
                     'PART_SHOW_RELATED': True,
                     'PART_TEMPLATE': False,
                     'PART_TRACKABLE': False,
                     'PART_VIRTUAL': False,
                     'PURCHASEORDER_REFERENCE_PREFIX': 'PO',
                     'REPORT_DEBUG_MODE': True,
                     'REPORT_DEFAULT_PAGE_SIZE': 'A4',
                     'REPORT_ENABLE_TEST_REPORT': True,
                     'SALESORDER_REFERENCE_PREFIX': 'SO',
                     'STOCK_ALLOW_EXPIRED_BUILD': False,
                     'STOCK_ALLOW_EXPIRED_SALE': False,
                     'STOCK_ENABLE_EXPIRY': False,
                     'STOCK_GROUP_BY_PART': True,
                     'STOCK_OWNERSHIP_CONTROL': False,
                     'STOCK_STALE_DAYS': 0},
 'USER_SETTINGS': {'HOMEPAGE_BOM_VALIDATION': True,
                   'HOMEPAGE_BUILD_OVERDUE': True,
                   'HOMEPAGE_BUILD_PENDING': True,
                   'HOMEPAGE_PART_LATEST': True,
                   'HOMEPAGE_PART_STARRED': True,
                   'HOMEPAGE_PO_OUTSTANDING': True,
                   'HOMEPAGE_PO_OVERDUE': True,
                   'HOMEPAGE_SO_OUTSTANDING': True,
                   'HOMEPAGE_SO_OVERDUE': True,
                   'HOMEPAGE_STOCK_DEPLETED': True,
                   'HOMEPAGE_STOCK_EXPIRED': True,
                   'HOMEPAGE_STOCK_LOW': True,
                   'HOMEPAGE_STOCK_NEEDED': True,
                   'HOMEPAGE_STOCK_RECENT': True,
                   'HOMEPAGE_STOCK_STALE': True,
                   'LABEL_INLINE': True,
                   'PART_RECENT_COUNT': 10,
                   'REPORT_INLINE': False,
                   'SEARCH_PREVIEW_RESULTS': 10,
                   'STOCK_RECENT_COUNT': 10},
```

So there's definitely something there. Is it a bug on my end, maybe some database migration that didn't run well?
I made sure to run `inv update` before running the server, and after encountering the error I tried a `inv migrate` which gives me `No migrations to apply`.

Is there a way to fix this?

Kind regards,

**Comment by eeintech** [comment] 2021-08-20 14:23
That's weird, have you tried changing user? Does it stick to empty JS file?

**Comment by matmair** [comment] 2021-08-20 20:04
@Guusggg could you please paste the debug information from the information-modal? I can not reproduce the error rn.

**Comment by SchrodingersGat** [comment] 2021-08-22 14:49
@Guusggg I did manage to replicate this, but after trying to hunt down the source of the issue the problem has now disappeared. 

I think that this may be caused by a server-side caching issue.

Can you check something for me? If you remove the `{% debug ... %}` call from the template, does the javascript file then render correctly?

**Comment by SchrodingersGat** [comment] 2021-09-12 13:15
@Guusggg closing this for now, please let me know if you can replicate this and wish to re-open

**Closed by SchrodingersGat** 2021-09-12 13:15 UTC
Labels: bug, question, javascript
