### ISSUE TITLE
[BUG] Opening "Add Part Category" from "Create Part" dialogue brakes "Default Location" pop-up

### ISSUE THREAD

**Issue by Acvarium** [inventree/InvenTree#2421] opened 2021-12-04 17:10 UTC
**Describe the bug**   
When you work on "Create part" dialogue, and decided to create new category directly from this window by clicking "Add Part Category" on the top right, the "Default Location" pop-up list will no longer work.
You don't need to create category, it is enough to just click on the "Add Part Category" button for bug to occur.

**Steps to Reproduce**
1. Click on green button "New Part" for dialogue on appear;  
2. Click "Add Part Category" in a top right corner of a window; 
3. Close the "Add Part Category" window by clicking on a cross icon;
4. Scroll down to "Default Location" section and try to unfold the list; 

**Deployment Method**
- [ ] Docker
- [X] Bare Metal

**Version Information**
InvenTree-Version: 0.5.3
Django Version: 3.2.5
Commit Hash: 5ec998922
Commit Date: 2021-10-20
Database: sqlite3
Debug-Mode: True
Deployed using Docker: False

**Comment by matmair** [comment] 2021-12-04 22:46
@Acvarium thanks for the report! Can reproduce, we will have to look into that

**Comment by SchrodingersGat** [comment] 2021-12-05 05:39
Looks like this is happening because both the "new part" and "new category" forms have a field called "default_location"

Perhaps the jquery code does not differentiate correctly between the two field instances.

**Comment by SchrodingersGat** [comment] 2021-12-05 06:16
Two other bugs I have found while looking here:

- If you open a "secondary" modal (as above) and then close it, pressing the same button again (on the "primary" modal) does not open the secondary modal again. In fact all secondary modals are disabled until you close and re-open the primary modal

- If you open a "secondary" modal, the primary modal still has focus for the "escape" key, and so pressing escape actually closes the first modal..

**Comment by SchrodingersGat** [comment] 2022-01-19 08:40
@Acvarium now fixed in master

**Closed** 2022-01-19 08:39 UTC
Labels: bug, user interface
