### ISSUE TITLE
[FR] Editing the left parts menu

### ISSUE THREAD

**Issue by Allys1098** [inventree/InvenTree#3665] opened 2022-09-08 14:17 UTC
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

I would like to use InvenTree for a smaller scale and do not have any use for the "purchase orders" menus from the homepage. These can be hidden in the main settings but there is no option to add a 'part category' yourself. It would be nice if the menu (I have shown it below as well) was more customizable. 

![image](https://user-images.githubusercontent.com/56094708/189144242-8a01bf53-349c-43eb-ab5a-90d6078693fa.png)

### Suggested solution

The solution I'm thinking of is that that entire menu is customizable. People could add a shortcut to an item they need often or a shortcut to a category. Deleting the existing ones and adding the new shortcuts would then be found on the same place as the current settings for it are. 

### Describe alternatives you've considered

An alternative to what we want already kind of exists in the subscribed categories, but it would be more user friendly for it to be available in that main left parts menu. 

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment] 2022-09-08 15:32
hi there @EstelleSevers !
Thanks for the idea - I think this is a duplicate/extension of https://github.com/inventree/InvenTree/issues/3062 . Would you agree and could you maybe add your idea there if you see fit?

**Comment by SchrodingersGat** [comment] 2022-10-18 02:23
Duplicate of https://github.com/inventree/InvenTree/issues/3062

**Closed by SchrodingersGat** 2022-10-18 02:23 UTC
Labels: enhancement, user interface
