### ISSUE TITLE
Asset management feature

### ISSUE THREAD

**Issue by lettore** [inventree/InvenTree#1946] opened 2021-08-11 08:18 UTC
Currently I use Snipe-it for mange my assets, intended as tools, software licenses etc.
This is overly complicated for the average user, as this software is really well designed it would be possible to add just some new features to enable management of assets.
One of the missing features is the ability to assign a stock/asset to a specific person instead of a location, this is useful when you give something to someone and you want to track where your assets are.
Next can be useful also to add reminders for maintenance checks, as well keep track of repair events and costs.

**Comment by matmair** [comment] 2021-08-11 08:34
@lettore I do not mean to disregard you but as far as I see it InvenTree is meant for the SME EEs and hobbyists. Tracking stuff down to a specific person does not really make sense for that. Inventory and asset-management are two different kinds of things. The first is for manufacturing the later for logs and life-cycle management for assets.

There is a lot of complex business logic needed for states, maintenance checks, events etc. I know of a software that is well maintained, very agile with its states, checks etc. and meant for exactly what you are describing: [snipe-it](https://github.com/snipe/snipe-it). I keep several deployments running for different orgs and I honestly do not know how we should make something simpler than that while also enabling all the features you listed.

I think this proposal is a prime example of feature creep but @SchrodingersGat is the maintainer and if he is willing to accept a PR for this stuff why not. It certainly will add a lot of complexity and maintenance-cost for a fringe use-case.

**Comment by lettore** [comment] 2021-08-11 09:07
> @lettore I do not mean to disregard you but as far as I see it InvenTree is meant for the SME EEs and hobbyists. Tracking stuff down to a specific person does not really make sense for that. Inventory and asset-management are two different kinds of things. The first is for manufacturing the later for logs and life-cycle management for assets.
> 
> There is a lot of complex business logic needed for states, maintenance checks, events etc. I know of a software that is well maintained, very agile with its states, checks etc. and meant for exactly what you are describing: [snipe-it](https://github.com/snipe/snipe-it). I keep several deployments running for different orgs and I honestly do not know how we should make something simpler than that while also enabling all the features you listed.
> 
> I think this proposal is a prime example of feature creep but @SchrodingersGat is the maintainer and if he is willing to accept a PR for this stuff why not. It certainly will add a lot of complexity and maintenance-cost for a fringe use-case.

As you said if your target audience is the hobbyist market it's difficult to imagine to manage two different system (Inventree and Snipe-it) just to take track of some assets.
Obviously, this means that the functionality should be reduced to the essential, because if you need more than just basic asset management you should use a dedicated solution.

**Comment by SchrodingersGat** [comment] 2021-08-12 13:04
@lettore would you say this request is a duplicate of https://github.com/inventree/InvenTree/issues/656 ?

There have been a few other requests for similar "lending" features too. I think it would be well received if such functionality could be added in a "simple" manner.

However "simple" integrations are never simple, as @matmair rightfully pointed out above ;)

I think the furthest I'd like to see the scope creep is to allow "lending" to "customers" (but a "customer" could be a client, workmate, parent, whoever)...

This actually is somewhat related to the concept of an "RMA" or "product return" which is a feature I want to add in the future.

**Comment by matmair** [comment] 2021-12-04 20:40
@SchrodingersGat should we close this as a duplicate of #656 ? Has a big potential to be a feature creeper.

**Comment by SchrodingersGat** [comment] 2021-12-04 20:55
Duplicate of #656

**Closed by SchrodingersGat** 2021-12-04 20:55 UTC
Labels: question, stock
