### ISSUE TITLE
(AGAIN) Bare metal installation using quick script is not working

### ISSUE THREAD

**Issue by LukeARESYS** [inventree/InvenTree#7439] opened 2024-06-13 09:03 UTC
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I've done a clean reinstall of Ubuntu in WSL on Windows 10 and tried reinstalling Inventree using the quick script, and I am again experiencing issues.

It looks like this time the script does not create the config.yaml file in /etc/inventree and the data file in /opt/inventree.

The result is that connecting to localhost gives 502 error

### Steps to Reproduce

Fresh install of inventree using quick script

### Relevant log output

```bash
### Installer for InvenTree - source: inventree/stable
### Detected distribution: Ubuntu 22.04
### Installing required packages for download
### Installing libssl1.1
deb http://security.ubuntu.com/ubuntu focal-security main
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Get:5 https://dl.packager.io/srv/deb/inventree/InvenTree/stable/ubuntu 20.04 InRelease [1863 B]
Get:6 http://security.ubuntu.com/ubuntu focal-security InRelease [128 kB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2983 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [446 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [13.2 kB]
Fetched 3572 kB in 3s (1201 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libssl1.1 is already the newest version (1.1.1f-1ubuntu2.22).
The following packages were automatically installed and are no longer required:
  fontconfig gettext javascript-common jq libdatrie1 libevent-2.1-7 libevent-extra-2.1-7 libexpat1-dev libffi7 libgraphite2-3 libharfbuzz0b libjq1 libjs-jquery libjs-sphinxdoc libjs-underscore
  libnginx-mod-http-geoip2 libnginx-mod-http-image-filter libnginx-mod-http-xslt-filter libnginx-mod-mail libnginx-mod-stream libnginx-mod-stream-geoip2 libonig5 libpango-1.0-0 libpangoft2-1.0-0 libpq5
  libpython3-dev libpython3.10-dev libthai-data libthai0 libxslt1.1 nginx nginx-common nginx-core python3-brotli python3-cffi python3-dev python3-pip python3-ply python3-pycparser python3-wheel
  python3.10-dev zlib1g-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
### Getting and adding key
### Adding package source
### Updating package lists
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 https://dl.packager.io/srv/deb/inventree/InvenTree/stable/ubuntu 20.04 InRelease [1863 B]
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Fetched 1863 B in 1s (2027 B/s)
Reading package lists... Done
### Setting installer args
### Installing InvenTree
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  inventree
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 0 B/64.5 MB of archives.
After this operation, 153 MB of additional disk space will be used.
Selecting previously unselected package inventree.
(Reading database ... 32177 files and directories currently installed.)
Preparing to unpack .../inventree_0.15.3-1716835122.d4d9aa9d.focal_amd64.deb ...
Unpacking inventree (0.15.3-1716835122.d4d9aa9d.focal) ...
Setting up inventree (0.15.3-1716835122.d4d9aa9d.focal) ...
# Setting base environment variables
# No config file found: /etc/inventree/config.yaml, using envs or defaults
# Collected environment variables:
#    INVENTREE_MEDIA_ROOT=/opt/inventree/data/media
#    INVENTREE_STATIC_ROOT=/opt/inventree/data/static
#    INVENTREE_BACKUP_DIR=/opt/inventree/data/backup
#    INVENTREE_PLUGINS_ENABLED=true
#    INVENTREE_PLUGIN_FILE=/etc/inventree/plugins.txt
#    INVENTREE_SECRET_KEY_FILE=/etc/inventree/secret_key.txt
#    INVENTREE_DB_ENGINE=sqlite3
#    INVENTREE_DB_NAME=/opt/inventree/data/database.sqlite3
#    INVENTREE_DB_USER=sampleuser
#    INVENTREE_DB_HOST=samplehost
#    INVENTREE_DB_PORT=123456
# Getting the IP address of the server via web service
IP address is xxxxxx
# No python environment found - using python3.9
# Setting up python environment
bash: line 1: python3.9: command not found
bash: line 1: env/bin/pip: No such file or directory
# Stopping nginx
# Setting up nginx to /etc/nginx/sites-enabled/inventree.conf
# Starting nginx
# (Re)creating init scripts
Nothing to do.
Nothing to do.
# Enabling InvenTree on boot
# Creating admin user data
# Stopping InvenTree
# Updating InvenTree
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.37.1)
bash: line 1: invoke: command not found
# Set permissions for data dir and media: /opt/inventree/data
chown: cannot access '/opt/inventree/data': No such file or directory
# Setting up InvenTree config values
# Writing the settings to the config file /etc/inventree/config.yaml
sed: can't read /etc/inventree/config.yaml: No such file or directory
sed: can't read /etc/inventree/config.yaml: No such file or directory
sed: can't read /etc/inventree/config.yaml: No such file or directory
sed: can't read /etc/inventree/config.yaml: No such file or directory
sed: can't read /etc/inventree/config.yaml: No such file or directory
sed: can't read /etc/inventree/config.yaml: No such file or directory
sed: can't read /etc/inventree/config.yaml: No such file or directory
sed: can't read /etc/inventree/config.yaml: No such file or directory
sed: can't read /etc/inventree/config.yaml: No such file or directory
sed: can't read /etc/inventree/config.yaml: No such file or directory
sed: can't read /etc/inventree/config.yaml: No such file or directory
sed: can't read /etc/inventree/config.yaml: No such file or directory
sed: can't read /etc/inventree/config.yaml: No such file or directory
chown: cannot access '/opt/inventree/data': No such file or directory
chown: cannot access '/etc/inventree/config.yaml': No such file or directory
# Setting up InvenTree site URL
# Starting InvenTree
####################################################################################
This InvenTree install uses nginx, the settings for the webserver can be found in
/etc/nginx/sites-enabled/inventree.conf
Try opening InvenTree with either
http://localhost/ or xxxxx

Admin user data:
   Email: admin@example.com
   Username: admin
   Password: xxxxx
####################################################################################
### Install done!
```

**Comment by matmair** [comment] 2024-06-13 15:33
Currently, only python3.9 is tested for. Using other versions is possible but you might run into issues. You can manually bypass this by setting SETUP_PYTHON to the python run command you want to use eg. `python3.10`

**Comment by matmair** [comment] 2024-06-13 15:37
Duplicate of https://github.com/inventree/InvenTree/issues/7437

**Comment by matmair** [comment] 2024-06-13 15:38
See https://github.com/inventree/InvenTree/issues/7377

**Closed** 2024-06-13 22:25 UTC
Labels: duplicate, question, setup
