### ISSUE TITLE
[BUG] Deleting a stock location messes up the location hierarchy

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#2733] opened 2022-03-09 22:41 UTC
**Describe the bug**

When you delete a stock sublocation something is wrong with the algorithm, the resulting location hierarchy will be wrong. 

**Steps to Reproduce**

I'm sorry but I tested it on demo.inventree.org (after restoring my database).
Just delete a stock sublocation and you will see the results:
<img width="1222" alt="Képernyőfotó 2022-03-09 - 23 23 16" src="https://user-images.githubusercontent.com/580623/157550002-bb1e6b1d-7963-4d60-8b64-470894fe41d8.png">

**Comment by SchrodingersGat** [comment] 2022-03-10 00:21
This looks to be a duplicate of https://github.com/inventree/InvenTree/issues/2636, which we could never duplicate. 

Thanks for reporting this @rkalman we will have to look closely at this one.

**Closed** 2022-03-10 05:07 UTC
Labels: bug, question

**Comment by rkalman** [comment] 2022-03-10 07:37
Thank you fixing this so fast!

**Comment by SchrodingersGat** [comment] 2022-03-10 07:42
No worries, this bug has been around for a while it seems. Happy to have isolated it now.
