### ISSUE TITLE
frontend-download: GitHub doesn't allow artifact downloads from anonymous users

### ISSUE THREAD

**Issue by StormTrooper** [inventree/InvenTree#5413] opened 2023-08-08 12:30 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When updating to the latest version I've seen this error scrolling by. 

InvenTree database migrations completed!
Found workflow QC (run 7178-1)
Found artifact frontend-build with id 849374398 (1.21MB).

GitHub doesn't allow artifact downloads from anonymous users. Either download the following file
via your signed in browser, or consider using a point release download via invoke frontend-download --tag <git-tag>

    Download: https://github.com/InvenTree/inventree/suites/14905555951/artifacts/849374398 manually and
    continue by running: invoke frontend-download --file <path-to-downloaded-zip-file>

Not sure if this is a critical error and if I didn't see the error scrolling past and did nothing would the upgrade have failed?

I downloaded the file manually and then ran the ```invoke frontend-download```

### Steps to Reproduce

1. invoke update

### Expected behaviour

Is there a workaround for this other than having to download the file manually and then 
```invoke frontend-download```

Is this required during each upgrade?

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.0 dev
Django Version: 3.2.20
Commit Hash: af14cef
Commit Date: 08/08/2023
Commit Branch: master
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
Installer: GIT

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Running migrations:
  No migrations to apply.
System check identified no issues (1 silenced).
========================================
InvenTree database migrations completed!
Found workflow QC (run 7178-1)
Found artifact frontend-build with id 849374398 (1.21MB).

GitHub doesn't allow artifact downloads from anonymous users. Either download the following file
via your signed in browser, or consider using a point release download via invoke frontend-download --tag <git-tag>

    Download: https://github.com/InvenTree/inventree/suites/14905555951/artifacts/849374398 manually and
    continue by running: invoke frontend-download --file <path-to-downloaded-zip-file>
render stock.js
render helpers.js
render part.js
render model_renderers.js
render news.js
render barcode.js
```

**Comment by SchrodingersGat** [comment] 2023-08-09 12:16
@StormTrooper thanks for reporting. This should not impact current behaviour but is important for future work. 

@wolflu05 @matmair we'll need to address this!

**Comment by matmair** [comment] 2023-08-10 09:25
This is intended behaviour; as discussed previously we do not want to have compiled forntend-files in the repo. This is the only feasible way to provide frontend files for non-release git-based installs.

**Comment by SchrodingersGat** [comment] 2023-08-10 10:40
Yep, but should we make "compile frontend" an "opt-in" option until we switch to the new UI? We are going to get a *lot* of confused users if we make it the default behaviour for invoke update, I think

**Comment by matmair** [comment] 2023-08-10 19:13
Several new features I am building won't get a C UI interface (from me at least - #5095, #2284 ) so it would be good to push the change to P UI.

**Comment by wolflu05** [comment] 2024-03-21 13:35
The only options I see here to make this a fully automated process for any commit are either:

1. Configure a Github PAT somewhere which the script uses to download the artifact (not sure security wise if people would love that, because I wouldn't)
2. Provide our own artifact server which doesn't have this auth requirement
3. (Don't care, because ppl. should either use docker or the package installer which both have a build included. And if they still want to use this setup method, they need to work with this semi automated process)

**Comment by matmair** [comment] 2024-03-21 16:24
I am for 3

**Comment by SchrodingersGat** [comment] 2024-03-21 22:28
3) also. If people need a github account because they *really* don't want to use docker / installer / install node, then that does not seem like a massive burden.

**Comment by wolflu05** [comment] 2024-03-22 05:51
So if I understand the issue right we could close it?

**Comment by SchrodingersGat** [comment] 2024-03-22 05:54
I'm happy to close if @matmair is also

**Comment by matmair** [comment] 2024-03-22 06:29
Happy to close, maybe we should add some info about this to the FAQ / install docs

**Comment by SchrodingersGat** [comment] 2024-03-24 04:30
Closing, replaced by https://github.com/inventree/InvenTree/issues/6833

**Closed by SchrodingersGat** 2024-03-24 04:30 UTC
Labels: question, setup
