### ISSUE TITLE
Initial database setup script does not work with postgress:14 image

### ISSUE THREAD

**Issue by EliasJRH** [inventree/InvenTree#7715] opened 2024-07-23 00:36 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The [initial database setup script](https://docs.inventree.org/en/latest/start/docker_install/#initial-database-setup) step does not work with the postgres version update from 13 to 14. According to the log output, this seems to be caused by a version mismatch between the postgres server at 14.12 and the `pg_dump` command at 13.15. This causes further issues when trying to run the application using docker compose.

I've circumvented this issue by changing the postgres version image back to 13.

### Steps to Reproduce

1. Download the required files from the [Docker installation page](https://docs.inventree.org/en/stable/start/docker_install/#docker-installation) to the working directory
2. In the working directory, run the initial database setup script `docker compose run --rm inventree-server invoke update`
3. Wait for the steps to complete and observe that the script fails due to an error with `pg_dump`

Optionally:
4. Change the postgres image version from 14 to 13 on line 41 of `docker-compose.yml`
5. Run the initial database setup script again
6. Observe that the script completes and that the remaining setup steps also complete without error

### Expected behaviour

The initial database setup script completes without any `pg_dump` errors and the InvenTree database is created correctly.

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.15.5
Django Version: 4.2.14
Commit Hash: cc45357
Commit Date: 2024-07-12

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Backing up InvenTree database...
Python version 3.11.9 - /usr/local/bin/python3
/root/.local/lib/python3.11/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
  warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
Backing Up Database: inventree
 pg_dump --dbname=postgresql://pguser:pgpassword@inventree-db:5432/inventree --format=custom
CommandConnectorError: Error running:  pg_dump --dbname=postgresql://pguser:pgpassword@inventree-db:5432/inventree --format=custom
pg_dump: error: server version: 14.12 (Debian 14.12-1.pgdg120+1); pg_dump version: 13.15
pg_dump: error: aborting because of server version mismatch

  File "/root/.local/lib/python3.11/site-packages/dbbackup/utils.py", line 120, in wrapper
    func(*args, **kwargs)
  File "/root/.local/lib/python3.11/site-packages/dbbackup/management/commands/dbbackup.py", line 93, in handle
    self._save_new_backup(database)
  File "/root/.local/lib/python3.11/site-packages/dbbackup/management/commands/dbbackup.py", line 106, in _save_new_backup
    outputfile = self.connector.create_dump()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/db/base.py", line 92, in create_dump
    return self._create_dump()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/db/postgresql.py", line 112, in _create_dump
    stdout, stderr = self.run_command(cmd, env=self.dump_env)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/db/base.py", line 171, in run_command
    raise exceptions.CommandConnectorError(

Traceback (most recent call last):
  File "/home/inventree/src/backend/InvenTree/manage.py", line 24, in <module>
    main()
  File "/home/inventree/src/backend/InvenTree/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/utils.py", line 120, in wrapper
    func(*args, **kwargs)
  File "/root/.local/lib/python3.11/site-packages/dbbackup/management/commands/dbbackup.py", line 93, in handle
    self._save_new_backup(database)
  File "/root/.local/lib/python3.11/site-packages/dbbackup/management/commands/dbbackup.py", line 106, in _save_new_backup
    outputfile = self.connector.create_dump()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/db/base.py", line 92, in create_dump
    return self._create_dump()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/db/postgresql.py", line 112, in _create_dump
    stdout, stderr = self.run_command(cmd, env=self.dump_env)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/db/base.py", line 171, in run_command
    raise exceptions.CommandConnectorError(
dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_dump --dbname=postgresql://pguser:pgpassword@inventree-db:5432/inventree --format=custom
pg_dump: error: server version: 14.12 (Debian 14.12-1.pgdg120+1); pg_dump version: 13.15
pg_dump: error: aborting because of server version mismatch
```

**Comment by SchrodingersGat** [comment] 2024-07-23 00:41
@EliasJRH thanks for reporting. This is likely due to this recent update: https://github.com/inventree/InvenTree/pull/7699

We will look into it and issue an update.

**Comment by SchrodingersGat** [comment] 2024-07-23 00:43
Ah, ok.. The issue is not with the update directly. The files you downloaded are linked to the "master" branch of InvenTree - this means that your docker compose file is "too new" to run the stable image.

Your solution of using `postgres:13` in your compose file is the correct one.

**Comment by EliasJRH** [comment] 2024-07-23 00:46
> Ah, ok.. The issue is not with the update directly. The files you downloaded are linked to the "master" branch of InvenTree - this means that your docker compose file is "too new" to run the stable image.
> 
> Your solution of using `postgres:13` in your compose file is the correct one.

That's good to know, thank you for responding so quickly!

**Comment by SchrodingersGat** [comment] 2024-07-23 00:46
@matmair FYI here's the reason for the issue:

"stable" docs point to "master" docker compose file

![image](https://github.com/user-attachments/assets/3f3e9a4c-9504-45a7-acb1-d48255c2c871)

Note that this has been fixed in the master branch by using a relative linking system.

![image](https://github.com/user-attachments/assets/5449ec10-1792-4675-894a-fd406768e80a)

**Comment by matmair** [comment] 2024-07-24 20:51
@SchrodingersGat should I backport these changes to stable?
@EliasJRH we have rolled back the change altogether. Can we close this issue as it was resolved?

**Comment by SchrodingersGat** [comment] 2024-07-24 21:32
Did we push the original changes to stable? If so we should backport the fix too.

**Comment by EliasJRH** [comment] 2024-07-25 00:21
@matmair Yes I think rolling back the change should be good enough to close this issue 👍

**Closed** 2024-07-25 00:38 UTC
Labels: bug, docker, setup
