### ISSUE TITLE
Can't open any stock item in the browser - Internal Server Error, but possible in the App

### ISSUE THREAD

**Issue by mittkkoo** [inventree/InvenTree#5619] opened 2023-09-25 14:33 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I can't open any stock items from the browser. The error is cited below. But I can open the stock item from the Android app!

The error message is 
```
Internal Server Error
The server raised an internal error
Refer to the error log in the admin interface for further details
```

### Steps to Reproduce

1. Create a trackable part
2. Create a stock item
3. Try to open the stock item in the browser and in the Android app

### Expected behaviour

I expect to be able to open the item.

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

Installed from the Digitalocean 1-click-install and then update to 0.12.7

# Version Information:
InvenTree-Version: 0.12.7
Django Version: 3.2.19
Commit Hash: 6563b4c4
Commit Date: None
Commit Branch: 0.12.x
stable
Database: postgresql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-163-generic-x86_64-with-glibc2.29
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Type:
AttributeError
Path:
http://xxx.xxx.xxx/stock/item/5/
Info:
'str' object has no attribute 'removesuffix'
When:
Sept. 25, 2023, 2:23 p.m.
Data:
Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
response = response.render()

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 105, in render
self.content = self.rendered_content

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
return template.render(context, self._request)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 170, in render
return self._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/library.py", line 192, in render
output = self.func(*resolved_args, **resolved_kwargs)

File "/opt/inventree/InvenTree/generic/states/tags.py", line 14, in status_label
state = {cls.tag(): cls for cls in inheritors(StatusCode)}.get(typ, None)

File "/opt/inventree/InvenTree/generic/states/tags.py", line 14, in <dictcomp>
state = {cls.tag(): cls for cls in inheritors(StatusCode)}.get(typ, None)

File "/opt/inventree/InvenTree/generic/states/states.py", line 108, in tag
ref_name = cls.__name__.removesuffix('Status')

AttributeError: 'str' object has no attribute 'removesuffix'
```

**Comment by wolflu05** [comment] 2023-09-25 15:18
Hello @mittkkoo ,

This is related to your python version, at least python v3.9 is required ([docs](https://docs.inventree.org/en/stable/start/intro/#python-requirements)).

Duplicate of #5131, #5393

**Comment by wolflu05** [comment] 2023-09-25 15:18
Duplicate of #5393

**Comment by SchrodingersGat** [comment] 2023-09-25 23:45
Yep, you need to update your python version to at least `3.9`

**Comment by mittkkoo** [comment] 2023-09-26 19:05
I didn't understand how the Digitalocean droplet is configured. There is a dev environment and docker-compose, but there are no containers running, nor there seems to by a python virtual environment... Obviously just installing python 3.9 on ubuntu and setting it as the default python3 won't work. Can I ask for some hints on correctly updating python?

**Comment by mittkkoo** [comment] 2023-09-27 09:22
OK, it worked after I removed and installed inventree using the script. Here the summary of the whole procedure that worked for me.

Freeze requirement & take a back-up of existing env
```
pip freeze > requirements.txt
deactivate
mv env env_old
```
Install Python 3.9 & activate virutal environment
```
sudo apt-get install python3.9-venv
python3.9 -m venv env
source env/bin/activate
python --version
```
Install requirements
```
sudo apt-get install python3.9-dev
pip3 install -r requirements.txt
inv update #not sure if needed!
```
Remove and then reinstall inventree:
```
deactivate
apt remove inventree
wget -qO install.sh https://get.inventree.org && bash install.sh
```

**Closed** 2023-09-27 23:13 UTC
Labels: question, setup

**Comment by SchrodingersGat** [comment] 2023-09-28 02:04
@mittkkoo thanks for sharing your solution - hopefully it will be useful if anyone else runs into the same issue.
