### ISSUE TITLE
Cannot login .../platform

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#6727] opened 2024-03-16 08:31 UTC
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [X] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

According to 
https://github.com/wolflu05/inventree-dymo-plugin/issues/2
Login to mysite/platform is not possible. My Inventree username and password does not work. The reset password. function seems
to do nothing. 
![login](https://github.com/inventree/InvenTree/assets/10836099/f06d3865-4968-4c27-a2d0-033145ab5e1a)

Installed version: 0.15.0 dev 
Comit hash 9ff09c8 
Commit Date 2024-03-15 
commit Branch master

What am I missing?

### Steps to Reproduce

Try to login mysite/platform

### Relevant log output

```bash
16/Mar/2024 08:28:43] "GET /platform HTTP/1.1" 200 636
[16/Mar/2024 08:28:44] "GET /static/web/assets/index-19438820.js HTTP/1.1" 200 3172
[16/Mar/2024 08:28:44] "GET /static/web/assets/MobileAppView-ba0ea19c.js HTTP/1.1" 200 491
[16/Mar/2024 08:28:44] "GET /static/web/assets/DesktopAppView-747a2232.js HTTP/1.1" 200 57459
[16/Mar/2024 08:28:44] "GET /static/web/assets/vendor-c50a8390.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/BaseContext-a18d7fff.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/links-4c07aa67.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /assets/MobileAppView-ba0ea19c.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /assets/BaseContext-a18d7fff.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /assets/links-4c07aa67.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /assets/vendor-c50a8390.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/BaseContext-a18d7fff.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/MobileAppView-ba0ea19c.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/messages-c6f93367.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /assets/DesktopAppView-747a2232.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/links-4c07aa67.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/vendor-c50a8390.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /assets/Layout-502d6a83.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /assets/globalStyle-ed485bee.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /assets/index-19438820.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /assets/auth-5d446b44.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /assets/Placeholder-3be5212c.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /assets/IconSearch-7a732453.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/DesktopAppView-747a2232.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/Layout-502d6a83.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/globalStyle-ed485bee.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/Layout-502d6a83.js HTTP/1.1" 200 13953
[16/Mar/2024 08:28:44] "GET /static/web/assets/index-19438820.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/Placeholder-3be5212c.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/auth-5d446b44.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/IconSearch-7a732453.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/globalStyle-ed485bee.js HTTP/1.1" 200 2672
[16/Mar/2024 08:28:44] "GET /static/web/assets/auth-5d446b44.js HTTP/1.1" 200 1474
[16/Mar/2024 08:28:44] "GET /static/web/assets/Placeholder-3be5212c.js HTTP/1.1" 200 300
[16/Mar/2024 08:28:44] "GET /static/web/assets/IconSearch-7a732453.js HTTP/1.1" 200 376
[16/Mar/2024 08:28:44] "GET /favicon.ico HTTP/1.1" 302 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/Logged-In-f593a4c9.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /assets/Logged-In-f593a4c9.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/Logged-In-f593a4c9.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/Login-0de01776.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/LanguageSelect-81ff2ae2.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /assets/LanguageSelect-81ff2ae2.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /assets/Login-0de01776.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /assets/IconEdit-7ee5da4a.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/use-form-5049279f.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/IconTrash-2361ddde.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /assets/IconTrash-2361ddde.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /assets/use-form-5049279f.js HTTP/1.1" 301 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/Login-0de01776.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/LanguageSelect-81ff2ae2.js HTTP/1.1" 200 1589
[16/Mar/2024 08:28:44] "GET /static/web/assets/IconEdit-7ee5da4a.js HTTP/1.1" 304 0
[16/Mar/2024 08:28:44] "GET /static/web/assets/IconTrash-2361ddde.js HTTP/1.1" 200 348
[16/Mar/2024 08:28:44] "GET /static/web/assets/use-form-5049279f.js HTTP/1.1" 200 8928
[16/Mar/2024 08:28:44] "GET /static/web/assets/IconEdit-7ee5da4a.js HTTP/1.1" 200 312
```

**Comment by matmair** [comment] 2024-03-16 13:59
@SergeoLacruz can you open your browser's console (f12 normally) and post the web call that get's issues once you log in? To me, it seems like your inventree API server is not even connected - indicated by no version number showing in the section below the authentication box.

**Comment by wolflu05** [comment] 2024-03-16 14:14
Also the lingui compile step seems to be missing and secondly maybe the wrong server is configured?

**Comment by SergeoLacruz** [comment] 2024-03-16 14:33
Here the login try:
![console](https://github.com/inventree/InvenTree/assets/10836099/6ee779a5-4222-407b-b7f2-d7301c83082e)

The rest of Inventree works just fine
![rest](https://github.com/inventree/InvenTree/assets/10836099/2fa4fbb9-efa0-4418-9ea3-b65c5525b468)

The server runs ubuntu 22.4 lts. The Inventree installation started with 0.10.0 and was regularaly updated using git pull. 
There have never been problems with Inventree.

**Comment by SergeoLacruz** [comment] 2024-03-16 14:58
Some good news: I added my host to this list:
![list](https://github.com/inventree/InvenTree/assets/10836099/38ac88b8-c4d3-40d0-b5cc-665662df0324)

Now I get a 6cPKtu welcome back wuoever this is:
![success](https://github.com/inventree/InvenTree/assets/10836099/550f18ad-0621-4a85-bea2-03ffcbff71af)

But nothing more happens. I always end up in the login page. A snippet from the log. 

16/Mar/2024 14:57:10] "GET /platform/user/token/ HTTP/1.1" 200 636
[16/Mar/2024 14:57:10] "GET /assets/IconEdit-7ee5da4a.js HTTP/1.1" 301 0
[16/Mar/2024 14:57:10] "GET /assets/use-form-5049279f.js HTTP/1.1" 301 0
[16/Mar/2024 14:57:10] "GET /assets/Login-0de01776.js HTTP/1.1" 301 0
[16/Mar/2024 14:57:10] "GET /assets/LanguageSelect-81ff2ae2.js HTTP/1.1" 301 0
[16/Mar/2024 14:57:10] "GET /static/web/assets/Login-0de01776.js HTTP/1.1" 200 6508
[16/Mar/2024 14:57:10] "GET /assets/IconTrash-2361ddde.js HTTP/1.1" 301 0
[16/Mar/2024 14:57:10] "GET /static/web/assets/IconEdit-7ee5da4a.js HTTP/1.1" 200 312
[16/Mar/2024 14:57:10] "GET /static/web/assets/use-form-5049279f.js HTTP/1.1" 200 8928
[16/Mar/2024 14:57:10] "GET /static/web/assets/Login-0de01776.js HTTP/1.1" 200 6508
[16/Mar/2024 14:57:10] "GET /static/web/assets/LanguageSelect-81ff2ae2.js HTTP/1.1" 200 1589
[16/Mar/2024 14:57:10] "GET /static/web/assets/IconTrash-2361ddde.js HTTP/1.1" 200 348
[16/Mar/2024 14:57:10] "GET /static/web/assets/use-form-5049279f.js HTTP/1.1" 200 8928
[16/Mar/2024 14:57:10] "GET /static/web/assets/IconEdit-7ee5da4a.js HTTP/1.1" 200 312
[16/Mar/2024 14:57:10] "GET /static/web/assets/Logged-In-f593a4c9.js HTTP/1.1" 200 370
[16/Mar/2024 14:57:10] "GET /static/web/assets/LanguageSelect-81ff2ae2.js HTTP/1.1" 200 1589
[16/Mar/2024 14:57:10] "GET /static/web/assets/IconTrash-2361ddde.js HTTP/1.1" 200 348
[16/Mar/2024 14:57:10] "GET / HTTP/1.1" 302 0
[16/Mar/2024 14:57:10] "GET / HTTP/1.1" 302 0
EMAIL_HOST is not configured
EMAIL_HOST_USER is not configured
DEFAULT_FROM_EMAIL is not configured
EMAIL_HOST is not configured
EMAIL_HOST_USER is not configured
DEFAULT_FROM_EMAIL is not configured
[16/Mar/2024 14:57:10] "GET /accounts/login/?next=/ HTTP/1.1" 200 8301
[16/Mar/2024 14:57:10] "GET /accounts/login/?next=/ HTTP/1.1" 200 8301

**Comment by SchrodingersGat** [comment] 2024-03-16 22:52
Can you please provide the initial server logs, as the server it booting up?

**Comment by wolflu05** [comment] 2024-03-17 08:08
What's interesting is that your server was not autoselected by PUI. Normally this is only the case when you build the frontend yourself with `VITE_DEMO` or use a development version by running `npm run dev`. 

How do you run InvenTree? In docker? Or do you build PUI yourself?

**Comment by SergeoLacruz** [comment] 2024-03-17 08:42
Morning,
Here is the log:
[log.txt](https://github.com/inventree/InvenTree/files/14626714/log.txt)

I did not touch PUI so far and did nothing in that area so far. I just write plugins. 
This is a bare metal installation I started with 0.10.0 just using git clone and regularly updated it using git pull and invoke update. No Docker. No venv. The machine is used exclusively for Inventree. 
The platform login does not save my server. After restart it always shows
![login](https://github.com/inventree/InvenTree/assets/10836099/fd7ae42b-f20c-425b-b1f9-08bb667dabb0)

Sorry for the trouble...

**Comment by SchrodingersGat** [comment] 2024-03-17 09:26
@SergeoLacruz thanks for the log - but it does not show anything suspicious.

Can you please try something for me?

In the "server selection" window (in PUI / platform / react interface) try selecting a different host, attempting a login, and then re-selecting the `http://192.168.1.40:8123` address

**Comment by SergeoLacruz** [comment] 2024-03-17 13:34
I set it up like here:
![hosts](https://github.com/inventree/InvenTree/assets/10836099/6a5a81cf-0fc4-4c3b-bb2c-0af7a2df8ce5)

First I tried the GUICZC. Nothing happens in the log. Then I tried my server. This happens in the log:
[log.txt](https://github.com/inventree/InvenTree/files/14627524/log.txt)
I get a 6cPKtu welcome back as shown in the pic above. But the login screen remains. 

Here is the config if it is useful:
[config.txt](https://github.com/inventree/InvenTree/files/14627530/config.txt)

I did not do anything of the things described here so far:
https://docs.inventree.org/en/latest/develop/react-frontend/

Michael

**Comment by wolflu05** [comment] 2024-03-17 13:53
Oh, please try removing the /api suffix from the configured url.

And if you run InvenTree from git, how did you got the frontend? Do you always checkout a specific tag via git, or did you manually downloaded the frontend from GitHub actions artifacts after running invoke update?

**Comment by SergeoLacruz** [comment] 2024-03-17 14:20
Removed /api. Same result.
For the second question: ??? honestly, no clue. I used the guide here:
https://github.com/SergeoLacruz/inventree-docs/blob/master/docs/start/install.md
long time ago. Nothing more. Works fine so far. 
Michael

**Comment by wolflu05** [comment] 2024-03-17 14:59
I suspect that your PUI build is not up to date like the commit you're using. This could happen with your deployment method if you do not specifically download the frontend build. Could you please look for the modification dates and git information for the files in `InvenTree/web/static/web` and their subfolders with the following commands and provide their results:
```bash
cd your-inventree-folder # there should be plugin, order, part, ... folders too
git status
git rev-parse HEAD
ls -l InvenTree/web/static/web
ls -l InvenTree/web/static/web/assets
```

**Comment by SergeoLacruz** [comment] 2024-03-17 15:43
Here it is:
[bla.txt](https://github.com/inventree/InvenTree/files/14627919/bla.txt)
The files you mentioned are quite old.

**Comment by wolflu05** [comment] 2024-03-17 20:31
Yes, that confirms my assumption. You run a very old version of PUI from the very beginning where we have incorrectly have committed the build. The issue is that we cannot commit those huge bundles (2.5mb) for every commit.

So stop your InvenTree service and either:
- need to be build on your machine (requires nodejs to be installed, and then run `invoke frontend-compile`) 
- you can semi automatically download a prebuilt bundle for your specific commit ref by using the `invoke frontend-download` helper. Just run that command and follow the steps that are shown on the terminal.

But note that you have to do this each time you update your installation, so
you can also run either of these commands automatically during invoke update when using the frontend `invoke update --frontend` command (this will attempt to build if node is available, and else fallback to download the frontend)

If you just want to use PUI I would recommend that you go with the downloaded build as this has not so much potential for issues and you also dont clutter your server with a nodejs installation.

If you got this far and started InvenTree again, I would also recommend to remove the `session-settings` value from your browser's local storage where you already tried PUI so that the hostlist correctly reinitalizes and the login should then just work without any changes. Actually it should also work without login if you are already logged into CUI.

Hope that helps you. If you encounter any errors during that process feel free to ask.

**Comment by SergeoLacruz** [comment] 2024-03-19 10:39
Thanks for the help. I used option 2. Downloading the file and install is easy. Here is how the file structure now looks like:
[ls-lR.txt](https://github.com/inventree/InvenTree/files/14649316/ls-lR.txt)

And here is the result:
![Bildschirmfoto vom 2024-03-19 07-17-24](https://github.com/inventree/InvenTree/assets/10836099/f0734ca9-e65e-4cea-975d-bc4a13d716cd)

**Comment by wolflu05** [comment] 2024-03-19 22:06
Hey Michael, sorry for the inconvenience, we missed to compile the translations for those builds before creating the build. A fix has just been merged (#6754). But this also shows how rare such a bare metal installation directly from source is, because this issue must have existed since the very beginning, but nobody else has noticed it.

Since you already run the unstable 0.15.0 dev version, you would just need to update to the latest commit and download the bundle again with the same command.

**Comment by SergeoLacruz** [comment] 2024-03-20 09:27
looks better now :-)
![Bildschirmfoto vom 2024-03-20 10-26-25](https://github.com/inventree/InvenTree/assets/10836099/1e6cbca6-3385-44e8-a0c8-6fb2dd1828c0)

Many Thanks for the good help.

**Comment by SchrodingersGat** [comment] 2024-03-20 10:05
@SergeoLacruz great, thanks for reporting back!

**Closed** 2024-03-20 10:06 UTC
Labels: question, setup
