### ISSUE TITLE
Purchase Order import

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#1826] opened 2021-07-17 15:22 UTC
- When I click "Purchase Order" -> "Upload File", left menu disappears.
- Can't upload file with non-ascii filename. `'ascii' codec can't encode character '\u0430' in position 62: ordinal not in range(128)`
- Field names selector width is limited by table column width. ![PO_import1](https://user-images.githubusercontent.com/10057327/126041518-174acfe1-94df-401b-a096-f7a0a9e69f37.png)
- On the second step wizard uses not my default currency but first in the list (Australian dollars)
- Decimal separator (comma) has been removed 
![PO_import2](https://user-images.githubusercontent.com/10057327/126043332-d9bc9108-0c04-4a84-b0a2-19c49011555f.png)

Anyway, great tool for table import.
FYI: I'm using latest pull from master.

**Comment by eeintech** [comment] 2021-07-19 16:26
Hello @sintech I cannot reproduce the ascii problem, I have put this string in both filename and file content: `людиа`
Do you know exactly which char fails?

The number conversion is cause by the decimal separator being a comma `,` instead of dot `.`. I will have to take a look how to solve this. I'll look into the currency matching too after that.

Thanks for reporting on this new tool!

**Comment by sintech** [comment] 2021-07-19 16:47
Pls find attached error screenshot and xls.
If I remove "копия_" from filename it is loading fine.
![изображение](https://user-images.githubusercontent.com/10057327/126196449-a0019564-5468-4552-b13e-d317366d0ea8.png)
[копия_orders_web_17-07-21_01.04.42.xls](https://github.com/inventree/InvenTree/files/6842579/_orders_web_17-07-21_01.04.42.xls)

**Comment by eeintech** [comment] 2021-07-19 19:34
@sintech I still can't reproduce your error even with your file. When I download it, the first part of the name does not appear... and if I add it manually it works fine too.
Anyway, I added a check on the encoding to avoid hitting the debug page (or at least I think it should do that).

For the resizing of the dropdown, I previously tried the `dropdownAutoWidth` option from the `select2` API : https://select2.org/configuration/options-api

But it does not work, the dropdown spans over the entire page... So I don't know how to auto size it to the content of the dropdown, sorry for that.

The rest of the issues you encountered should be fixed in #1844

**Closed** 2021-07-19 21:58 UTC
