### ISSUE TITLE
AttributeError - 'str' object has no attribute 'removesuffix'

### ISSUE THREAD

**Issue by markwski** [inventree/InvenTree#6059] opened 2023-12-09 12:56 UTC
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

Hello,

I have a problem with stock items. As far as I observed, it only happens in two cases described.
I tried reinstalling Ubuntu and Inventree, but the error still occurs.
Inventree was installed using "quick script" (wget -qO install.sh https://get.inventree.org && bash install.sh).

### Steps to Reproduce

1. Creating new part, then adding it to stock by clicking "New Stock Item" and then "Submit". This error has no effect on the actual stock quantity, for example if I type 10pcs in the Quantity field, it will be added to the database.
![image](https://github.com/inventree/InvenTree/assets/153366640/3931d5cf-e0ae-4cc7-b2ef-46698e789848)
![image](https://github.com/inventree/InvenTree/assets/153366640/7c8ad855-ff65-4b91-84f7-8d0af267f4ed)
![image](https://github.com/inventree/InvenTree/assets/153366640/80444f3a-65ba-4317-ac0e-b96d4052ee69)

2. Searching for the parts and clicking on the stock item from the search results. I can't open stock item from the search results.
![search](https://github.com/inventree/InvenTree/assets/153366640/8b21e5c1-9913-475c-a100-ebe2e13717ff)
![image](https://github.com/inventree/InvenTree/assets/153366640/24f36cbb-4b5b-408e-83aa-12349758ecbf)

### Expected behaviour

No error.

### Deployment Method

- [ ] Docker
- [x] Bare metal

### Version Information

I'm running Ubuntu Server 20.04 LTS.

![about](https://github.com/inventree/InvenTree/assets/153366640/6cdeb67a-c704-4796-8ede-9088d6710d80)
![sys info](https://github.com/inventree/InvenTree/assets/153366640/296f5d3a-b1fe-4442-a109-7fc2b3dc36ee)

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Error object (22)
[HISTORY](http://192.168.2.24/admin/error_report/error/22/history/)

Type:
AttributeError
Path:
http://192.168.2.24/stock/item/20/
Info:
'str' object has no attribute 'removesuffix'
When:
Dec. 9, 2023, 11:41 a.m.
Data:
Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
response = response.render()

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 105, in render
self.content = self.rendered_content

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
return template.render(context, self._request)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 170, in render
return self._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/library.py", line 192, in render
output = self.func(*resolved_args, **resolved_kwargs)

File "/opt/inventree/InvenTree/generic/states/tags.py", line 14, in status_label
state = {cls.tag(): cls for cls in inheritors(StatusCode)}.get(typ, None)

File "/opt/inventree/InvenTree/generic/states/tags.py", line 14, in <dictcomp>
state = {cls.tag(): cls for cls in inheritors(StatusCode)}.get(typ, None)

File "/opt/inventree/InvenTree/generic/states/states.py", line 108, in tag
ref_name = cls.__name__.removesuffix('Status')

AttributeError: 'str' object has no attribute 'removesuffix'
```

**Comment by wolflu05** [comment] 2023-12-09 13:34
Hello, please search through the issues before opening a new one. There are now at min 5 of them. The recent is #5773. You need to update python to at least 3.9. This is the required minimum Python version.

**Comment by wolflu05** [comment] 2023-12-09 13:35
Duplicate of #5773

**Comment by SchrodingersGat** [comment] 2023-12-09 20:37
@markwski please update your python version and this error goes away :)

**Closed by SchrodingersGat** 2023-12-09 20:37 UTC
Labels: question, setup
