### ISSUE TITLE
[BUG] PO ID / SO ID pattern changed from 0.7.X to 0.8.X causing unexpected issues.

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#3524] opened 2022-08-12 11:36 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

After updating to 0.8.X I found out that there are new specifications on how you should name your PO ID and SO ID.
Previously On 0.8.X if you write the name wrong you get the error: "Reference must match required pattern: PO-{ref:04d}"

Previously, I created my own unique names without a pattern, now because those still exist, I get a bunch of errors on many different interfaces. and through the entire system. the solution was to go to /admin/ page and manually replace all POs and SO to the pattern mentioned above.

### Steps to Reproduce

1. from 0.7.X create PO / BO with unique names such as "PO-LCSC-PROTOTYPE-REV5"
2. Upgrade system to 0.8.X
3. Try to do operations on the BO/PO such as additional component, update status, changed to completed, etc ...
4. See that a lot of issues occur

### Expected behavior

The idea of the pattern is good but I wish I thought about it in previous builds. currently, I would just say the way to fix this behavior is through migration, when running the invoke update script all the BO/PO that doesn't stand on the pattern should be automatically renamed. But again, this might cause more issues if the company/user uses a third party that refers to those BOs/POs.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

InvenTree-Version: 0.8.0
Django Version: 3.2.14
Commit Hash: 6118d1319
Commit Date: 2022-08-01
Database: mysql
Debug-Mode: True
Deployed using Docker: False

**Comment by miggland** [comment] 2022-08-12 15:52
I know it doesn't solve your problem, but have you read about the pattern definition? It is not constant, and `PO-{ref:04d}` is simply the default.

See here: https://inventree.readthedocs.io/en/latest/buy/po/#purchase-order-reference

To match something like your example `PO-LCSC-PROTOTYPE-REV5`, you could use `PO-LCSC-PROTOTYPE-REV{ref:01d}`
Or to match `PO-LEED-PROTOTYPE-REV6`as well:
`PO-????-PROTOTYPE-REV{ref:01d}`

At the moment, there is no way to have a variable number of characters though.. so you can't match both `PO-LCSC` and `PO-LCSC-PROTOTYPE`

**Comment by Zontex** [comment] 2022-08-12 16:07
Is there a place to change the pattern in 0.8.X?

**Comment by miggland** [comment] 2022-08-12 16:09
Settings -> Purchase Orders

as well as Sales Orders, Build Orders - they each have their own reference pattern.

**Comment by matmair** [comment] 2022-08-16 17:21
@Zontex You basically spelt out our thinking process. It would be nice if the pattern was always followed but rewriting references is out of the question.
I do not see this as a bug, it was documented as a change in the release notes. @SchrodingersGat what do you think? I would suggest to close this as `wontfix`.

**Comment by SchrodingersGat** [comment] 2022-08-16 23:05
Agreed, not a bug. But I'm open to any improvements you can suggest to make the system work better.

**Closed by SchrodingersGat** 2022-08-16 23:05 UTC
Labels: question
