### ISSUE TITLE
[FR] More detailed stock status

### ISSUE THREAD

**Issue by wolflu05** [inventree/InvenTree#6464] opened 2024-02-10 11:17 UTC
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I want to track the stock status especially of used parts in a more detailed manner and not just "Ok", "Damaged", ... so that I can later use that information with a e-commerce software to display the status to the user.

### Suggested solution

I want to specify specific categories where I can rate the stock. 

E.g.:
| Name | Rating |
|--------|--------|
| Technical working | 1-6 |
| Optical appearance | 1-6 |

But I'm not sure where and how to implement that, curious about your thoughts.

### Describe alternatives you've considered

- Add that to the stock notes in a defined format
- Use a custom plugin with metadata or AppMixin and a custom model

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment] 2024-02-10 21:52
I think that to support this (and other users have request custom stock status codes too) we would need to reconsider how the stock status is handled entirely.

Currently, the "status" field is included in the decision of "is this stock item available" or "in stock". So, a "quarantined" item is not in stock, but a "damaged" item is. So, it affects core InvenTree business logic. Extending this field to allow custom values would make this very difficult to manage.

So, I do not have an immediate solution to this. But I think that we would potentially need to move away from the "status" value actually having an impact on business logic. Especially if users want custom values here to use to track properties of the stock item

**Comment by wolflu05** [comment] 2024-02-10 22:12
Maybe we can set the business logic state on a user defined status code. E.g. Ok means available, and damaged, quarantized, ... not available. Where ok, damaged, ... can be user defined and each assigned a business logic group (available/not available)


But I do not think that would solve my needs. Maybe I'm best with using a panel plugin in combination with metadata or a custom model.

**Comment by matmair** [comment] 2024-02-11 00:16
Removing the logic is probably difficult / a step back - not being able to use damaged stock for example is a very useful thing. But adding custom display states that are free text but always coupled to a business logic state should be very easy.
This is also is probably a duplicate of https://github.com/inventree/InvenTree/issues/4289 thinking more about it

**Comment by wolflu05** [comment] 2024-02-11 07:58
I think it's a bit different to stock status, I want to rate the stock in multiple categories, but not just one select. But after thinking a bit more about it, it seems like it's a niche use case, so I'll use a plugin and we can close this.

**Closed** 2024-02-11 07:58 UTC
Labels: enhancement
