### ISSUE TITLE
Unsuitable/Damaged stock items are included when allocating stock items

### ISSUE THREAD

**Issue by tehkillerbee** [inventree/InvenTree#4253] opened 2023-01-24 14:17 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

When allocating stock items for a build order, it seems "unsuitable" stock items are included in the available stock. 
Stock items with a status listed as "Damaged", "Atten. Needed etc." should probably not be possible to allocate.

Is this behavior intentional? It does not seem like a good idea to allow allocation of "Invalid" stock items, unless the user is aware of this.

### Steps to Reproduce

1. Create a build order that contains stock items, where one or more has been listed as "Damaged"
![image](https://user-images.githubusercontent.com/815886/214317989-90450532-3b38-4ad0-9699-10074fd20785.png)
3. When allocating stock items, you will see that the total stock item count includes "Damaged" stock items as well.
![image](https://user-images.githubusercontent.com/815886/214317725-febb4ea3-792e-461c-a84c-6286d1e37429.png)

### Expected behavior

Invalid stock items (Damaged, Attn. Needed) should not be possible to allocate. Alternatively, we should have a way to allow this.

Another alternative could be to display the stock item status when allocating the item:
![image](https://user-images.githubusercontent.com/815886/214317520-2ba48297-fcc1-4998-914f-2252d044e84b.png)

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.10.0 dev
Django Version: 3.2.16
Commit Hash: fb34409
Commit Date: 2022-12-19
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by matmair** [comment] 2023-02-01 18:17
Stock states are only there as a piece of information. They do not impact business logic. It would be easy to change that - we should be careful though as it could break existing instances.

**Comment by SchrodingersGat** [comment] 2023-02-01 23:31
I think this issue would be solved better by a "general purpose" solution which also addresses https://github.com/inventree/InvenTree/issues/4253

With the ability to define custom stock status codes, the user can define which codes are considered "in active stock"

**Comment by tehkillerbee** [comment] 2023-02-06 08:12
@matmair That makes sense. This could be solved by displaying the stock status in the drop-down menu so the user can avoid selecting stock items with an unsuitable status. This will not work for auto-allocation, however, if the user has used status as a way to differentiate stock items.

For instance, in our case some of our stock items are marked as "Attn. needed" since they are production samples. Therefore, they should not be used for production systems.

@SchrodingersGat A custom stock status (with the ability to mark as active stock) sounds like a good idea too.

**Comment by SchrodingersGat** [comment] 2023-05-12 11:58
Closing this issue as a duplicate of #4289

**Closed** 2023-05-12 11:58 UTC
Labels: question, stock
