### ISSUE TITLE
Only parameters with Choices seems to be searchable

### ISSUE THREAD

**Issue by Basilisvirus** [inventree/InvenTree#7582] opened 2024-07-08 08:40 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Using the demo website https://demo.inventree.org/, trying to search at Parameters tab, I notice that if I search "Green", I get the results of the parameters that have this color value. 
But if I search "220kR", which is also a parameter value, I do not see any results:

![image](https://github.com/inventree/InvenTree/assets/18421898/9b90f7b0-5e6d-4226-b712-114636e2be66)

As I understand the parameters value that have pre-defined values are included in the search results, while parameters without pre-defined values are not searchable?
I do not see that being an option to enable/disable in the settings/search settings.

### Steps to Reproduce

1. Go to Invetree's [demo website](https://demo.inventree.org/index/), log in as allaccess | nolimits. 
2. Click on parts, then parameters  
![image](https://github.com/inventree/InvenTree/assets/18421898/47b340b5-7696-4328-bf56-c863f34b274b)
3. Search for a parameter value that you see, which is not pre-defined. For example first thing you might see is "2 inches":
![image](https://github.com/inventree/InvenTree/assets/18421898/52991f4a-f3bf-4d10-bc02-db0c2b9f765a)
4. Observe there are no search results.
![image](https://github.com/inventree/InvenTree/assets/18421898/33e38896-b172-4ed2-95c7-a346ea8980a6)

### Expected behaviour

Expected behavior would be:
1. Go to Invetree's [demo website](https://demo.inventree.org/index/), log in as allaccess | nolimits. 
2. Click on parts, then parameters  
3. Search for a parameter value that you see, which is not pre-defined. For example first thing you might see is "2 inches":
4. There should be results that match the string "2 inches" search, since this is a value in a parameter.

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [X] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.16.0 dev
Django Version: 4.2.13
Commit Hash: 1d4114b
Commit Date: 2024-07-08

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.0-100-generic-x86_64-with
Installer: DOC

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment] 2024-07-08 14:18
@Basilisvirus the "search" input here does not search any parameter values at all - only the part fields (e.g. "name" / "description"). 

We have an open issue to implementing filtering and searching of parameters - https://github.com/inventree/InvenTree/issues/7346

If you would like to see this implemented / prioritized, you could consider support the issue with some funding

**Comment by SchrodingersGat** [comment] 2024-07-08 14:20
Duplicate of https://github.com/inventree/InvenTree/issues/7346

**Closed by SchrodingersGat** 2024-07-08 14:20 UTC
Labels: bug, duplicate, question
