### ISSUE TITLE
[BUG] Update instructions from 0.5.4 to 0.6.0

### ISSUE THREAD

**Issue by lettore** [inventree/InvenTree#2700] opened 2022-03-01 14:14 UTC
**Describe the bug**

I'm running 0.5.4 on Docker and tried to update to 0.6.0 with no luck.
I'm getting many errors like:
file "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value.
Every time I made an update in the past I had so many problems that I'm not sure if I should continue using this software.
From a developer point of view it should be stated in every major release if something breaks the past configuration, and which steps are required for make the new version working.
It's crystal clear that the software is under heavy development, and I'm into helping with debugging and resolving issues, but breaking changes should be listed in release notes.

**Comment by matmair** [comment] 2022-03-01 19:57
@lettore sorry to here that you feel this way.
If you are not happy to use a project that you never committed code to (as far as I can both remember and see in the codebase - feel free to correct me) for free with free support: I will not force you to.

This bug report will not help in any way with fixing a bug in this form. It is just general complaints and negativity plus a code reference without the error or when it occured  or what you were trying to do.

The codebase is tested by a CI, including migrations. So if you had unmodified code that was set up to the docs and ran the migrations with everything turned off it should run without problems.
If this is the case please fill in the bug report and I will try to reproduce and fix it. That would be helpfull. This is not.

**Comment by eeintech** [comment] 2022-03-01 20:09
I second @matmair's response, a bug is best solved with clear instructions to reproduce, which you did not provide.

Where in the update process did you get stuck?
https://inventree.readthedocs.io/en/latest/start/docker_prod/#updating-inventree

There is **_plenty_** of documentation on Docker setup, at least point out which step causes trouble.

On my barebone installations and following the **_correct_** process for updating, the update from `0.5.4` to `0.6.0` went without issue, there is no reason yours shouldn't if you follow the correct process.

**Comment by lettore** [comment] 2022-03-01 20:45
First of all thank you for quick response.
Yes, not everyone can contribute with code, so I contributed buying the Android app on Playstore for 10€, for a software that at the time was not "stable", so as the app is not useful alone I expect at least that the software is kept working.
Not everyone uses Docker Compose, as it's now quite unsupported, the way you force deploying the containers is a nightmare If you work in a Swarm or Kubernetes environment, because the container itself is recreated at every restart, so it's not possible to use the commands you propose in the Wiki.
Running `invoke update` in server container returns:
python3: can't open file 'InvenTree/script/translation_stats.py': [Errno 2] No such file or directory
Restarting the whole stack now gives me this error in Chrome:
jquery_3.3.1_jquery.min.js:2 jQuery.Deferred exception: inventreeLoad is not defined ReferenceError: inventreeLoad is not defined
    at loadTableFilters (https://inventree.ecasa.one/static/i18n/it.filters.js:52:24)
    at setupFilterList (https://inventree.ecasa.one/static/i18n/it.filters.js:272:19)
    at loadPartTable (https://inventree.ecasa.one/static/i18n/it.part.js:841:5)
    at loadSimplePartTable (https://inventree.ecasa.one/static/i18n/it.part.js:580:5)
    at HTMLDocument.<anonymous> (https://inventree.ecasa.one/index/:542:1)
    at l (https://inventree.ecasa.one/static/script/jquery_3.3.1_jquery.min.js:2:29375)
    at c (https://inventree.ecasa.one/static/script/jquery_3.3.1_jquery.min.js:2:29677) undefined
w.Deferred.exceptionHook @ jquery_3.3.1_jquery.min.js:2
jquery_3.3.1_jquery.min.js:2 Uncaught ReferenceError: inventreeLoad is not defined
    at loadTableFilters (it.filters.js:52:24)
    at setupFilterList (it.filters.js:272:19)
    at loadPartTable (it.part.js:841:5)
    at loadSimplePartTable (it.part.js:580:5)
    at HTMLDocument.<anonymous> ((index):542:1)
    at l (jquery_3.3.1_jquery.min.js:2:29375)
    at c (jquery_3.3.1_jquery.min.js:2:29677)
The entire home page is messed up and not working anymore.
This kind of update process should be managed  by the container itself, when starting and seeing that DB or local storage have an older version a script should take care of doing anything needed for update the system to a working state, not leaving the system broken.

**Closed** 2022-03-01 20:51 UTC
Labels: bug, question

**Comment by lettore** [comment] 2022-03-01 20:54
Was my mistake of running invoke update inside the container not with the correct entrypoint.
Starting the container with the command invoke update did the trick.
It's not really comfortable as I'm running the stack in Swarm.

**Comment by matmair** [comment] 2022-03-01 21:55
> Was my mistake of running invoke update inside the container not with the correct entrypoint.
> Starting the container with the command invoke update did the trick.

That is somewhat known, at least two ppl tried to work on that - myself being one of them - and failed. The problem is that you have to lock database access before running the migrations. They get blocked elsewise / django rolls back the changes.

The current solution works but is not 100 intuitive for scaling / distributed solutions. I am not super knowledgeable in this are - if you have an idea how that could be better I would be thankfull @lettore.

> It's not really comfortable as I'm running the stack in Swarm.

I am running some instances with kubernetes (not my choice). I have a maintenance script that brings down all pods, starts a script with the command entrypoint and then starts everything back up. Maybe that is feasible for you? I do it with simple bash, not sure if that is possible with swarm.

**Comment by SchrodingersGat** [comment] 2022-03-02 11:13
@lettore we can only support so many use-cases in the documentation, but I'm glad you got it figured out.

FYI - I have added a "FAQ" entry, as it seems that the `invoke update` steps is an easy one for people to miss :) 

https://github.com/inventree/inventree-docs/pull/247
