### ISSUE TITLE
How to itterate through the parts list in template

### ISSUE THREAD

**Issue by alxrMironov** [inventree/InvenTree#8551] opened 2024-11-25 11:42 UTC
### Body of the issue

Im trying to create a report template for stocketaking for warehouse workers. 
From my view it must be a table by each part, with next collums.

- Part name
- Part available stock value (even if == 0)

The problem is - there is no example, how to itterate through each part in database\category. 
Default stocktake report use stock item, so by definition it exclude parts with zero available stock and duplicate rows with same part but multiple stock items. This turn stocktake in hell.

So, how can i itterate throug parts in template?

**Comment by SchrodingersGat** [comment] 2024-11-25 11:46
Duplicate of https://github.com/inventree/InvenTree/issues/8545 - please discuss in #8545 to avoid duplicate issues.

**Closed** 2024-11-26 12:31 UTC
Labels: duplicate, documentation
