### ISSUE TITLE
Build Output (in progress) issue after updating

### ISSUE THREAD

**Issue by wolffam** [inventree/InvenTree#1640] opened 2021-06-07 02:15 UTC
I don't remember exactly what version of Inventree I was running previously (it was probably 4-6 months older) but when I updated today, I can see an issue with build outputs I had not completed.  They no longer show any stock items allocated and there's a spinning/loading icon next to the build output continuously. 
<img width="863" alt="Screen Shot 2021-06-06 at 7 09 03 PM" src="https://user-images.githubusercontent.com/11801197/120950236-3993a380-c6fb-11eb-92d9-2757ee90eb1f.png">

I am unsure if this is related but my Inventree System Information is showing some issues as well:
<img width="641" alt="Screen Shot 2021-06-06 at 7 09 25 PM" src="https://user-images.githubusercontent.com/11801197/120950297-592acc00-c6fb-11eb-9b29-7284ff4558bb.png">

Should I try downgrading or is this a known issue?  I don't want to lose all the information for the build outputs I had in progress.

**Comment by SchrodingersGat** [comment] 2021-06-07 03:25
Hey @wolffam the "Build" system received a monumental overhaul recently - I tried to ensure that existing builds migrated seamlessly but it appears that some edge cases may have been overlooked.

## System Information

Firstly, the "system information" display is not an issue here - it is simply showing that the [background worker](https://inventree.readthedocs.io/en/latest/admin/tasks/) has not been started. Refer to the docs [here](https://inventree.readthedocs.io/en/latest/start/development/#start-background-worker) or [here](https://inventree.readthedocs.io/en/latest/start/production/) (depending on your particular installation.

## Build Issues

On the page where you see the spinning icon, can you please open the developer interface for your browser (`Ctrl` + `Shift` + `I` on Firefox for e.g.)

Then click on the "console" tab (see example below) and you should see some javascript error messages

![image](https://user-images.githubusercontent.com/10080325/120954997-c427e180-c793-11eb-9abe-144382847311.png)

Please share a screenshot of those error messages here, so we can work out what's going on!

![image](https://user-images.githubusercontent.com/10080325/120954754-3946e700-c793-11eb-96d0-d30e05497a18.png)

**Comment by wolffam** [comment] 2021-06-07 03:38
Thanks @SchrodingersGat , 

<img width="797" alt="Screen Shot 2021-06-06 at 8 37 23 PM" src="https://user-images.githubusercontent.com/11801197/120955786-0a832f00-c707-11eb-9c76-b7faf51c2a15.png">

Feel free to let me know if I can get you any other info.

**Comment by wolffam** [comment] 2021-06-08 16:48
Unfortunately, I'm not getting too much back from that...

![Screen Shot 2021-06-08 at 9 43 12 AM](https://user-images.githubusercontent.com/11801197/121225378-51c00b80-c83e-11eb-937a-c86cb3804d50.png)

And that response is before I hit "Serial Number: LS16" to bring up the list of allocated stock items.
My already completed builds appear to be fine -- just the "in progress" ones

**Comment by wolffam** [comment] 2021-06-08 16:53
If it's easier, I can downgrade (I might need a build number to downgrade to) before the changes and upgrade once all of my build outputs are completed.

**Comment by wolffam** [comment] 2021-06-08 22:19
Ah good call:
![Screen Shot 2021-06-08 at 3 18 00 PM](https://user-images.githubusercontent.com/11801197/121264988-e9d4e980-c86c-11eb-935a-4b14b149d27b.png)


[inventree-traceback.txt](https://github.com/inventree/InvenTree/files/6619876/inventree-traceback.txt)

**Comment by SchrodingersGat** [comment] 2021-06-08 23:42
Huh, that's a very strange error to be seeing in this situation - I did not expect to see that...

I have submitted a fix here - https://github.com/inventree/InvenTree/pull/1647

Once that PR is merged, please try updating and see if the issue is fixed on your end :)

**Closed** 2021-06-09 00:02 UTC
Labels: bug, build

**Comment by wolffam** [comment] 2021-06-09 00:10
Seems like we're now getting to a new missing attribute:
![Screen Shot 2021-06-08 at 5 09 04 PM](https://user-images.githubusercontent.com/11801197/121273084-44c20d00-c87c-11eb-8788-047df8bc6a41.png)

[inventree-traceback2.txt](https://github.com/inventree/InvenTree/files/6620278/inventree-traceback2.txt)

We appreciate the help!

**Comment by SchrodingersGat** [comment] 2021-06-09 01:37
Ok this one was pretty embarrassing especially as I just looked over that code, and didn't see the obvious mistake...

Same process again - wait until https://github.com/inventree/InvenTree/pull/1649 is merged and then check :)

**Comment by SchrodingersGat** [comment] 2021-06-09 01:55
@wolffam merged in now, please let me know if you run into any other issues :)

**Comment by wolffam** [comment] 2021-06-09 02:01
All set!!! Thanks!!!

**Comment by SchrodingersGat** [comment] 2021-06-09 02:06
Great, happy to help :) Thanks for helping to squash some bugs!
