### ISSUE TITLE
[FR] Adding parts directly from suppliers

### ISSUE THREAD

**Issue by arkajyotidas** [inventree/InvenTree#6693] opened 2024-03-13 04:44 UTC
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

What if there was a feature like Kintree where we could directly add parts to our inventree with the part details and API of the suppliers?

1. We copy the part from our suppliers.
2. Select the supplier database and fetch it.
3. The inventree server then maps the product with the category we select.

Right now what we are doing is adding the part through Kintree. Adding this feature will cause Kintree to close. But KiCad now supports HTTP Library. So we can see this part on the KiCad in a much easier way.

### Suggested solution

N/A

### Describe alternatives you've considered

Kintree

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment] 2024-03-13 07:16
Duplicate of https://github.com/inventree/InvenTree/issues/3261

**Comment by SchrodingersGat** [comment] 2024-03-13 08:32
Closing this, please direct conversation to https://github.com/inventree/InvenTree/issues/3261

**Closed by SchrodingersGat** 2024-03-13 08:32 UTC
Labels: enhancement
