### ISSUE TITLE
One Liner script fails to install on Ubuntu server 22.04

### ISSUE THREAD

**Issue by mrkylegp** [inventree/InvenTree#3825] opened 2022-10-21 02:11 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

When attempting to use the one liner script to install on Ubuntu 22.04, the script halts with the following:

W: https://dl.packager.io/srv/deb/matmair/InvenTree/deploy-test/ubuntu/dists/22.04/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package inventree

### Steps to Reproduce

1. Install Ubuntu 22.04 Server
2. Run the one liner install script: curl https://raw.githubusercontent.com/InvenTree/InvenTree/master/contrib/install.sh | sh

### Expected behavior

Script completes and installs Inventree. 

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

0.9 dev

**Comment by matmair** [comment] 2022-10-22 00:46
@mrkylegp we currently do not support 22.04 due to changes that break multiple system integrations
![grafik](https://user-images.githubusercontent.com/66015116/197308821-0159e3bf-3004-4ea2-bc79-29b88b5f36dd.png)

![grafik](https://user-images.githubusercontent.com/66015116/197308799-96ba34db-8bfa-4e9d-b9ed-27f8457f52ca.png)

**Comment by Jnesselr** [comment] 2022-10-22 20:26
Is there a list of those breakages? Just found this issue out today. It's not the biggest deal, I can just re-image the VM. My VM server went down in an unrecoverable way so I'm having to rebuild it all anyway.

**Comment by matmair** [comment] 2022-10-22 20:47
hi there @Jnesselr !
Currently not in GitHub. I have some logs from my tests but after seeing it broke in multiple places I stopped pursuing it.
My current focus is on getting the deployment and updating story for most users streamlined as that creates many if not most user reports.
Getting 22.04 is on my personal roadmap but not in the near future. Ping me if you are interested in tackling it; most issues are related to plugin stuff -  most users can live without it but I can't.

**Comment by matmair** [comment] 2022-10-22 22:27
@mrkylegp are you ok with us closing this for now? It is a known limitation, not a bug in my view.

**Comment by Jnesselr** [comment] 2022-10-22 22:30
I'd highly recommend keeping it open. If the intention is that it should work on 22+ but currently you're being prevented from doing so by limitations in the OS, it's still an issue. Not all issues have to be bugs.

It also helps people find it more easily if it's open that if it's closed.

**Comment by mrkylegp** [comment] 2022-10-22 22:31
> @mrkylegp are you ok with us closing this for now? It is a known limitation, not a bug in my view.

@matmair Yeah, sure!

**Comment by mrkylegp** [comment] 2022-10-22 22:34
I will leave the closure upto the Devs. I just reported what didn't work however I do agree that leaving it open may help others to identify the fact that it doesn't work on 22.04 at the moment and help the Devs remember it needs attention still.

**Comment by matmair** [comment] 2022-10-22 23:18
I will close out this bug report as it is the intended behaviour / a documented limit of the project.
There are 2 new FRs covering the same topic in more actionable steps:
- https://github.com/inventree/InvenTree/issues/3835 to add a warning that links to the second FR (I am already working on this)
- https://github.com/inventree/InvenTree/issues/3836 covers the steps to add more packaging targets and a list of targets that would be easy

@Jnesselr the general intention is for it to run everywhere; not working on 22 is a limitation that was accepted to get the install instructions streamlined for anybody else; there are multiple issues regarding the core project not running open; for the installer, it is known and documented behaviour

**Closed by matmair** 2022-10-22 23:18 UTC
Labels: bug

**Comment by matmair** [comment] 2022-11-20 13:52
@mrkylegp there is *experimental* support for 22.04 now. You can check it out with:
```
wget -Nq https://raw.githubusercontent.com/matmair/InvenTree/22-04-installer-patch/contrib/install.sh && sudo bash install.sh master
```
Note: this installs libssl1.1 on your system. 22.04 by default ships with libssl3 but some of our deps need 1.1
