### ISSUE TITLE
Parts sidenav does not hold expanded state

### ISSUE THREAD

**Issue by ivladz** [inventree/InvenTree#1367] opened 2021-02-26 20:13 UTC
Parts sidenav does not remember the expanded state and it also clears the expanded state of Stock page:
![Parts-Sidenav](https://user-images.githubusercontent.com/2379634/109349969-6b38db00-787f-11eb-88fe-e558ac983b40.gif)

Also, as a "side note", is it possible to configure the sidenav to be fully expanded by default?

**Comment by SchrodingersGat** [comment] 2021-02-26 21:04
@ivladz this looks like a regression - previously it *did* remember the state of the sidenav. I'll have to look into this one.

**Comment by SchrodingersGat** [comment] 2021-02-28 02:30
Fixed in #1372

**Closed** 2021-02-28 02:29 UTC
