### ISSUE TITLE
"Issue Order" does not send emails

### ISSUE THREAD

**Issue by nikolai2111** [inventree/InvenTree#6669] opened 2024-03-10 10:21 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Today I filled in the email configuration in the .env file.

First I tested the email configuration by verifying the email address of the account. This has worked so far. Is there also a template that can be customized?

Next, I filled out and sent a test sales order, which never arrived at the email addresses defined in the customer directory. The purchase orders did not work either.

Since I thought at first that the mails ended up in spam, I manually sent myself a mail from the email, which arrived without any problems?

Do I need to configure anything else or is the system not working as I expect it to?
Which email would the order be sent to if I have an email on file with the customer as well as with a contact?

### Steps to Reproduce

1. Create customer with email
2. Create a sales or purchase order
3. Click on "Issue Order"
4. Check inbox for mails

### Expected behaviour

When I click "Issue Order" I should receive an email within few minutes, with the content of the sales order like in the report. 

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.14.1
Django Version: 4.2.10
Commit Hash: df0bb34
Commit Date: 2024-03-05

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.0-97-generic-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'InvenTreeBulkPlugin', 'slug': 'inventree-bulk-plugin', 'version': '1.2.3'}, {'name': 'ApprisePlugin', 'slug': 'apprise', 'version': '1.1'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment] 2024-03-11 19:07
@nikolai2111 mails are only sent internally - to the user/group assigned to be responsible.

**Comment by nikolai2111** [comment] 2024-03-11 19:21
Oh, so clicking on the issue order doesn't do anything other than inform the assigned user/group?

How likely is it to be integrated?

**Comment by matmair** [comment] 2024-03-11 20:13
Yes. InvenTree is meant for internal usage, not as an invoice / CRM tool so there is no communication to the outside (outside of registered users) if not specifically stated.

**Comment by matmair** [comment] 2024-03-11 20:14
This is not a bug, closing

**Closed by matmair** 2024-03-11 20:14 UTC
Labels: question, order

**Comment by SchrodingersGat** [comment] 2024-03-12 21:53
@nikolai2111 you could easily implement this behaviour in a [custom plugin](https://docs.inventree.org/en/stable/extend/how_to_plugin/)
