### ISSUE TITLE
Price value in  BOM is displayed with 1 digit instead of 2 after the dot.

### ISSUE THREAD

**Issue by StormTrooper** [inventree/InvenTree#4380] opened 2023-02-20 22:51 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When viewing the BOM for a part, if the price of a part  is for exampe 1.40 then it's displayed as 1.4

![Screenshot from 2023-02-20 22-46-02](https://user-images.githubusercontent.com/1429043/220209038-b6ddd8a9-85c0-42b3-a740-621a86ac9106.png)

The price however is shown correctly under stock

![Screenshot from 2023-02-20 22-50-15](https://user-images.githubusercontent.com/1429043/220209334-aa951a5c-1ce4-42bd-9222-6f86ec598b49.png)

### Steps to Reproduce

1. Create a part price of 1.40
2. Create a assemly part. 
3. Create BOM and add the above part. 
4. When viewing the  price range it's displayed of 1.4 instead of 1.40

### Expected behaviour

Expect price to be displayed with 2 decimals after the dot. 

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0 dev
Django Version: 3.2.16
Commit Hash: e78161bd0
Commit Date: 18/02/2023
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Active plugins: False

### Relevant log output

```shell
N/A
```

**Comment by simonkuehling** [comment] 2023-02-21 07:04
This is probably intentional right now for visibility of fractional cent/penny values (up to 5 decimal places I believe).

![CD4E2A98-CC3E-40EB-8AEC-A54724212F28](https://user-images.githubusercontent.com/296454/220271781-024e8d9d-dae9-43e4-b890-d312af1c6c30.jpeg)


It would be a good improvement to add trailing zeros to always show at least 2 decimal places, though - I agree.

**Comment by matmair** [comment] 2023-02-21 10:06
Not a bug - intended feature.

**Comment by StormTrooper** [comment] 2023-02-21 10:16
Thanks. Can this be raised as a FR?

**Comment by SchrodingersGat** [comment] 2023-02-21 13:59
The maximum number of trailing digits is limited by a configurable setting (between 2 and 6 places).

However, it does appear that if the value has a trailing zero (within this limit) it will be clipped.

To confirm, does the table below match what you are looking for?

| Value | Current | Desired |
| --- | --- | --- |
| 1.23456788 | 1.234 | 1.234 |
| 1.200 | 1.2 | 1.200 |
| 1.230 | 1.23 | 1.230 |

TBH I like that trailing zeroes are trimmed - it gives a cleaner look IMO but could be convinced otherwise.

@matmair what do you think?

**Comment by simonkuehling** [comment] 2023-02-21 14:55
> TBH I like that trailing zeroes are trimmed - it gives a cleaner look IMO but could be convinced otherwise.

I would personally vote for a mixed solution: trim trailing zeros, but only up to the 2 decimal places that are commonly used in accounting/finance for all currency values:

| Value | Current | Desired |
| --- | --- | --- |
| 1.23456788 | 1.234 | 1.234 |
| 1.200 | 1.2 | 1.20 |
| 1.230 | 1.23 | 1.23 |
| 1.000 | 1 | 1.00 |

**Comment by matmair** [comment] 2023-02-21 20:25
I like the current way as backfilled zeros are just waste IMO. If it is really wanted we can review a PR for an optional setting.

**Comment by SchrodingersGat** [comment] 2023-02-21 21:24
I'd be happy with an additional option to "pad" with (up to) two zeros if someone wants to submit.

**Comment by SchrodingersGat** [comment] 2023-04-03 14:15
Closed by https://github.com/inventree/InvenTree/pull/4527

**Closed by SchrodingersGat** 2023-04-03 14:15 UTC
Labels: help wanted, question, starter, pricing
