### ISSUE TITLE
Unable to delete some parts  -  IntegrityError

### ISSUE THREAD

**Issue by StormTrooper** [inventree/InvenTree#4419] opened 2023-02-25 13:50 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I have a few test parts I created while doing some troubleshooting last week. I've trying to delete them now and the delete  is failing with a foreign key constraint failure. This is not occuring on all parts - there are 10 or so parts I added than am unable to remove. 

(I've tried this after running the ```invoke update``` this time :)

### Steps to Reproduce

1. Find part to delete. 
2. Set to inactive
3. Try to delete part. 

### Expected behaviour

Should be able to delete part. 

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0 dev
Django Version: 3.2.16
Commit Hash: 5037e427b
Commit Date: 25/02/2023
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Active plugins: False

### Relevant log output

```shell
Traceback (most recent call last):

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
return self.cursor.execute(query, args)

File "/home/inventree/env/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
res = self._query(query)

File "/home/inventree/env/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
db.query(q)

File "/home/inventree/env/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
_mysql.connection.query(self, query)

MySQLdb.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`inventree`.`part_partpricing`, CONSTRAINT `part_partpricing_part_id_24e51ec7_fk_part_part_id` FOREIGN KEY (`part_id`) REFERENCES `part_part` (`id`))')


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/home/inventree/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/home/inventree/env/lib/python3.10/site-packages/rest_framework/generics.py", line 291, in delete
return self.destroy(request, *args, **kwargs)

File "/home/inventree/src/InvenTree/part/api.py", line 894, in destroy
return super(PartDetail, self).destroy(request, *args, **kwargs)

File "/home/inventree/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 91, in destroy
self.perform_destroy(instance)

File "/home/inventree/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
instance.delete()

File "/home/inventree/env/lib/python3.10/site-packages/mptt/models.py", line 1053, in delete
return super(MPTTModel, self).delete(*args, **kwargs)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/models/base.py", line 967, in delete
return collector.delete()

File "/home/inventree/env/lib/python3.10/site-packages/django/db/models/deletion.py", line 429, in delete
count = query.delete_batch(pk_list, self.using)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/models/sql/subqueries.py", line 43, in delete_batch
num_deleted += self.do_query(self.get_meta().db_table, self.where, using=using)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/models/sql/subqueries.py", line 23, in do_query
cursor = self.get_compiler(using).execute_sql(CURSOR)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
cursor.execute(sql, params)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
return super().execute(sql, params)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
return executor(sql, params, many, context)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
with self.db.wrap_database_errors:

File "/home/inventree/env/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
return self.cursor.execute(query, args)

File "/home/inventree/env/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
res = self._query(query)

File "/home/inventree/env/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
db.query(q)

File "/home/inventree/env/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
_mysql.connection.query(self, query)

django.db.utils.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`inventree`.`part_partpricing`, CONSTRAINT `part_partpricing_part_id_24e51ec7_fk_part_part_id` FOREIGN KEY (`part_id`) REFERENCES `part_part` (`id`))')
```

**Comment by SchrodingersGat** [comment] 2023-02-26 00:15
@StormTrooper thanks for reporting - a fix is incoming in https://github.com/inventree/InvenTree/pull/4422

**Comment by SchrodingersGat** [comment] 2023-02-26 05:36
Fix is merged in - please update and LMK if the problem is fixed for you :)

**Closed** 2023-02-26 05:36 UTC
Labels: bug, pricing
