### ISSUE TITLE
Add custom Stock Status Fields

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#5483] opened 2023-08-26 09:41 UTC
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Hi Team,

currently its possible to change stock status for stock items. the statuss are avileble from a dropdown list
![image](https://github.com/inventree/InvenTree/assets/130482028/c42629c2-c552-42f3-bf70-f787f3fdbe9f)

but i'd like to add custom stock statusses to the list like 'In test' in repair ...

### Suggested solution

i think that if we would be possible to add additional status via the admin panel that could solve this and does not sound to difficult.

### Describe alternatives you've considered

change location but its still availeble for sales in that way.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by wolflu05** [comment] 2023-08-26 16:44
Duplicate of #4289

**Comment by wolflu05** [comment] 2023-08-26 16:45
Hello @mabroens , this is already planned and there is already an issue for it and a started implementation in https://github.com/inventree/InvenTree/pull/4969 which I think is currently paused due to the frontend refactor.

**Closed by wolflu05** 2023-08-26 16:45 UTC
Labels: enhancement, triage:not-checked
