### ISSUE TITLE
[FR] slide out all sub-BOMs with one klick

### ISSUE THREAD

**Issue by RichiSeitz** [inventree/InvenTree#5289] opened 2023-07-19 12:42 UTC
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

It takes a lot of time and it is very confusing if you have to slide out each sub-BOM in a BOM to see all parts separatly.

### Suggested solution

If there would be a button which I could klick and all sub-BOMs would be open then, the solution is done.

### Describe alternatives you've considered

Shortcut instead of the button.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment] 2023-07-19 18:05
Duplicate of #5116

**Closed by matmair** 2023-07-19 18:05 UTC
Labels: enhancement, triage:not-checked
