### ISSUE TITLE
Language settings not saved

### ISSUE THREAD

**Issue by AlexandrePTJ** [inventree/InvenTree#3722] opened 2022-09-27 11:16 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Each time I startup firefox and log on inventree I have to change the language settings.

### Steps to Reproduce

I use a computer and browser set in french but I want inventree to use english.

1. Start up browser
2. Log in inventree => Inventree use french
3. Change to english => Inventree use english
4. Close browser
5. Start up browser
6. Log in inventree => Inventree still use french

### Expected behavior

Whenever I log on Inventree, language setting should be kept

### Deployment Method

- [x] Docker
- [ ] Bare metal

### Version Information

0.8.3

**Comment by SchrodingersGat** [comment] 2022-09-27 22:55
@AlexandrePTJ thanks for reporting. I have not been able to reproduce this.

Can you confirm that you are changing the language setting via the "settings" menu as below?

![image](https://user-images.githubusercontent.com/10080325/192651809-2a77f9c2-ad5c-4f7c-9269-87b059f19229.png)

Does the selected language change by itself back to the previous value/

**Comment by AlexandrePTJ** [comment] 2022-09-28 07:21
Yes I do.
Sorry I checked "Bare metal" for the installation, but it is "docker"

**Comment by SchrodingersGat** [comment] 2022-09-28 07:24
- Can you test if the problem persists for any other languages?
- Do any other settings get "reset" when you log out and log back in?

**Comment by AlexandrePTJ** [comment] 2022-09-28 07:30
* Just tested with german, italiano and norsk : it always come back to french
* Yes I did change some search settings and they have reset.
Just take note that settings are reset when I close and restart the browser, not when I logout/login.

**Comment by SchrodingersGat** [comment] 2022-09-28 07:32
Is your browser locale configured to request french language? I think it will use the browser request header language if provided.

**Comment by AlexandrePTJ** [comment] 2022-09-28 07:42
You are right when I change my browser settings, Inventree display the language I set in firefox. Then if now I select in Inventree french and restart my browser it came back to english ;)

**Comment by SchrodingersGat** [comment] 2022-09-28 08:27
Sounds like everything is working as intended then :)

**Comment by AlexandrePTJ** [comment] 2022-09-28 08:37
Not really. I mean, whatever my browser's settings are, I should be able to use another language settings in Inventree. This is not the case. I will not switch my browser language everytime I login on Inventree.

**Comment by SchrodingersGat** [comment] 2022-09-28 22:19
@AlexandrePTJ this is how django (the framework we use) prioritizes language lookup:

https://docs.djangoproject.com/en/4.1/topics/i18n/translation/#how-django-discovers-language-preference

@matmair any comments on this one? IIRC you had a lot to do with the language selection stuff

**Comment by AlexandrePTJ** [comment] 2022-10-05 12:12
From the django doc, using browser language is right after using session cookie. So If cookie is set, language should be kept to user selection.

**Comment by matmair** [comment] 2022-10-05 12:50
@SchrodingersGat we use the default stuff offered by Django; not sure what could break there. You can set Firefox to enforce a specific language and Django will respect that. Maybe that is what is going on in this edgecase.

I checked with Firefox on macOS and Windows and can not reproduce this.

**Comment by SchrodingersGat** [comment] 2022-10-06 11:31
@matmair thanks for checking!

@AlexandrePTJ are you able to test with a different browser and/or computer?

**Comment by AlexandrePTJ** [comment] 2022-10-06 18:47
I did reprodruce on mac, linux and windows. With firefox and any other browser.
Is there any public instance of Inventree I could try on ? I may come from my installation, but I don't see any error or warning message telling language settings is not saved.

**Comment by SchrodingersGat** [comment] 2022-10-10 02:33
@AlexandrePTJ you can try on https://demo.inventree.org - please check here and report back

**Comment by AlexandrePTJ** [comment] 2022-10-10 06:59
I have the exact same behaviour:
1. Login with engineer account. Display is in French.
2. Go to settings, change language to English. Display is in English.
3. Close the browser (not only the tab)
4. Login with engineer account. Display is back in French.

**Comment by SchrodingersGat** [comment] 2022-10-10 10:02
I can replicate this in edge browser, but it seems to work *as expected* in chrome.

@AlexandrePTJ what browsers have you tried this with?

**Comment by AlexandrePTJ** [comment] 2022-10-10 10:40
I tried with safari on mac and with firefox on either linux and windows.
Also just tried with chrome (fresh install) on windows and I also get the issue.

**Comment by SchrodingersGat** [comment] 2022-10-11 01:31
@AlexandrePTJ can you check if the session cookie is set in your browser?

**Comment by SchrodingersGat** [comment] 2022-10-11 10:40
![image](https://user-images.githubusercontent.com/10080325/195069336-de769628-c2d7-4294-8cab-081230a01995.png)

e.g. when changing language to italian, I see the following cookie

**Comment by AlexandrePTJ** [comment] 2022-10-11 16:06
Yes cookie is changed. But it looks to expires at session. So if session ends (closing browser) cookies expires. No ?

**Comment by SchrodingersGat** [comment] 2022-10-11 20:39
The cookie should persist. I have tested locally, and the cookie is persistent when:

- Logging out / in
- Closing the browser

(at least on chrome)

Can you confirm that the cookie resets when you close and re-open the browser?

**Comment by matmair** [comment] 2022-10-11 21:02
@SchrodingersGat @AlexandrePTJ this sounds like firefox is limiting the cookie lifetime. It tends to do that if it is set to more privacy-conscious presets.

**Comment by AlexandrePTJ** [comment] 2022-10-12 09:47
@SchrodingersGat I confirm that the cookie resets.
@matmair Then it depends on which kind of cookie this settings is written. Attached a screenshot of cookie used by another django based application (weblate)
<img width="959" alt="Sans titre" src="https://user-images.githubusercontent.com/3862081/195310276-eb1d4260-bd98-4368-b836-6b7ca3461a4b.png">

**Comment by matmair** [comment] 2022-10-12 10:08
This seems to be a client (/browser) issue and not related to InvenTree.
I checked with firefox 105 on MacOS, Debian and Windows again and it works as expected on the latest stable and latest master.
@AlexandrePTJ
1A) Could you try turning off privacy protections for the instance you are having problems with?
1B) Is your instance hosted with HTTPS? That might limit how long the browser stores the cookie
1C) You never posted the full version info; Could you post the Version presented in the `About` section? there should be a copy button there

**Comment by AlexandrePTJ** [comment] 2022-10-12 13:09
A) Turning off privacy settings did not change anything. Not a good approach anyway :)
B) No, only http
C) Sorry I missed this point:

```
# Version Information:
InvenTree-Version: 0.8.3
Django Version: 3.2.15
Commit Hash: f9d2b14
Commit Date: 2022-09-23
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
```

**Comment by AlexandrePTJ** [comment] 2022-10-12 13:14
I dig a bit into django documention and into weblate code too understand how weblate does to make it works.
This settings [LANGUAGE_COOKIE_AGE](https://docs.djangoproject.com/en/3.2/ref/settings/#language-cookie-age) tooks my attention. I added `LANGUAGE_COOKIE_AGE = 12096000` into `InvenTree/settings.py`, then everything is working perfectly.

**Comment by SchrodingersGat** [comment] 2022-10-12 13:26
@AlexandrePTJ very interesting, I wonder why the cookie is *not* being deleted otherwise then. Nice work figuring this out

**Comment by matmair** [comment] 2022-10-12 21:41
@AlexandrePTJ PR to fix this is in review now.

**Closed** 2022-10-12 23:56 UTC
Labels: bug, user interface

**Comment by AlexandrePTJ** [comment] 2022-10-13 07:44
@matmair @SchrodingersGat Thanks you for the work done.
I take this opportunity to say congratulations, InvenTree is an excellent application !
