### ISSUE TITLE
[BUG] RuntimeError: Model class django.contrib.sessions.models.Session doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS

### ISSUE THREAD

**Issue by cdwilson** [inventree/InvenTree#2429] opened 2021-12-06 15:45 UTC
**Describe the bug**
Running `inv worker` repeatedly shows the following errors:

```
08:47:59 [Q] ERROR Failed [seven-uncle-tennessee-north] - Model class django.contrib.sessions.models.Session doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS. : Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/envs/inventree/lib/python3.10/site-packages/django_q/cluster.py", line 436, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/Users/chris/Projects/inventree/InvenTree/InvenTree/tasks.py", line 240, in delete_expired_sessions
    from django.contrib.sessions.models import Session
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/envs/inventree/lib/python3.10/site-packages/django/contrib/sessions/models.py", line 10, in <module>
    class Session(AbstractBaseSession):
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/envs/inventree/lib/python3.10/site-packages/django/db/models/base.py", line 113, in __new__
    raise RuntimeError(
RuntimeError: Model class django.contrib.sessions.models.Session doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

**Steps to Reproduce**
1. `inv worker`

**Expected behavior**
No errors in the worker logs.

**Deployment Method**
- [ ] Docker
- [x] Bare Metal

**Version Information**
# Version Information:
InvenTree-Version: 0.6.0 dev
Django Version: 3.2.5
Commit Hash: b7f3a044d
Commit Date: 2021-12-06
Database: sqlite3
Debug-Mode: True
Deployed using Docker: False

**Comment by matmair** [comment] 2021-12-06 19:44
@cdwilson have you tried running `inv update` after pulling the update? Was this a fresh install or an upgrade from 0.5.x?

**Comment by cdwilson** [comment] 2021-12-06 22:17
I upgraded using `inv update` from 0.5.0 dev:

# Version Information:
InvenTree-Version: 0.5.0 dev
Django Version: 3.2.5
Commit Hash: b3c8bd777
Commit Date: 2021-09-24
Database: sqlite3
Debug-Mode: True
Deployed using Docker: False

**Comment by SchrodingersGat** [comment] 2021-12-06 22:23
Did you stop the worker processes before calling `invoke update`?

**Comment by cdwilson** [comment] 2021-12-07 17:16
> Did you stop the worker processes before calling `invoke update`?

Yes, nothing was running when I ran the update.  I ran the `inv update`, and then ran `inv server` and `inv worker` after the update.

**Comment by cdwilson** [comment] 2021-12-07 17:23
I don't know hardly anything about how Django works, but I noticed there is a task that uses `django.contrib.sessions` and it looks like this was removed from `INSTALLED_APPS` in #2371.  Could this be the issue?

https://github.com/inventree/InvenTree/blob/f2b966fac591119677a98b0e433e4b21988ad27c/InvenTree/InvenTree/tasks.py#L240

**Comment by SchrodingersGat** [comment] 2021-12-07 22:43
@cdwilson the change in #2371 moved from using the django built-in session management to using [django-user-sessions](https://github.com/jazzband/django-user-sessions)

But, your question has made me realise what the issue is!

@matmair the error message here is from the *old* background task which was responsible for culling old sessions. This task looks for django.contrib.sessions which is no longer used!

I'll make a PR to fix this...

**Comment by SchrodingersGat** [comment] 2021-12-08 11:50
@cdwilson should be fixed in master now :)

**Closed** 2021-12-08 11:49 UTC
Labels: bug, question
