### ISSUE TITLE
Chosen currency is not selected for purchase orders, default currency is selected

### ISSUE THREAD

**Issue by tomse** [inventree/InvenTree#6664] opened 2024-03-07 20:36 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When importing a csv file for a purchase order, the chosen currency for the supplier isn't used, default currency is being used though.

![310299656-a8171c5c-1eb1-436a-b4f3-7e1a1f5a3427_2](https://github.com/inventree/InvenTree/assets/1444539/eeb754f5-1337-4853-b925-f9c48c423f1d)

### Steps to Reproduce

have a dealer, select a currency for this dealer
choose a different default currency
make a purchase order
import a csv file for that purchase order, and go through the steps for importing.

### Expected behaviour

Chosen currency for dealer should be used/selected

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.13.5 & 0.14.1

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment] 2024-03-07 20:39
this is not a bug; we do not support currencies on import - that was already made clear in the related post. Please use the correct template in the future, we request different information on them

**Comment by tomse** [comment] 2024-03-07 20:44
sorry, I thought you wanted me to make a separate bug report for this.
should I create a feature request?

**Comment by SchrodingersGat** [comment] 2024-03-12 21:56
@tomse no need to create a separate issue, but please ensure that any future issues use the appropriate template :)

**Comment by tomse** [comment] 2024-03-12 22:10
> @tomse no need to create a separate issue, but please ensure that any future issues use the appropriate template :)

I will. I just didn't understand your reply properly, thus it became a bug report rather than a feature request.

**Comment by SchrodingersGat** [comment] 2024-07-17 07:22
@tomse this will be addressed in https://github.com/inventree/InvenTree/pull/7671 - note that all importing improvements require the new user interface

**Closed** 2024-07-17 07:44 UTC
Labels: enhancement, question, import / export
