### ISSUE TITLE
Dropdown filter not working when adding parameter to part.

### ISSUE THREAD

**Issue by alcorhythm** [inventree/InvenTree#2494] opened 2022-01-03 17:02 UTC
**Describe the bug**
When adding a new Parameter to an existing Part, the dropdown list is not filtered as you type. It just briefly says "Searching..." then goes back to displaying the whole list. Other dropdowns are filtered correctly.

**Steps to Reproduce**
1. Go to any part.
2. Open the Parameters tab
3. New Parameter
4. Type something in the Template box

**Expected behavior**
The parameter list is filtered based on what is typed.

**Screenshots**
![image](https://user-images.githubusercontent.com/60521324/147958977-08cbbc51-1bbe-4662-9574-ef02eff9724e.png)

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
InvenTree-Version: 0.5.4
Django Version: 3.2.5
Commit Hash: 66a08fe
Commit Date: 2021-11-03
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by SchrodingersGat** [comment] 2022-01-04 08:33
@alcorhythm thanks for reporting - this bug has already been found and fixed in the development 0.6.x branch. The next release is not too far away now :)

Duplicate of https://github.com/inventree/InvenTree/issues/2414

**Closed by SchrodingersGat** 2022-01-04 08:33 UTC
Labels: wontfix
