### ISSUE TITLE
Include test results in stock grid and filters

### ISSUE THREAD

**Issue by Kedarius** [inventree/InvenTree#917] opened 2020-08-20 12:11 UTC
It would be great if user would be able to show test results in the stock grid and be able to filter by them. For example filter: all items with all tests passed or items with failed specific test(s),.....

**Comment by SchrodingersGat** [comment] 2020-09-05 13:45
Similar to https://github.com/inventree/InvenTree/issues/821

**Comment by eeintech** [comment] 2020-10-13 01:44
@Kedarius Would #821 meet your requirement?

**Comment by eeintech** [comment] 2022-03-10 21:03
@SchrodingersGat I would close and keep #821 as reference

**Comment by SchrodingersGat** [comment] 2022-03-15 11:59
Duplicate of #821

**Closed by SchrodingersGat** 2022-03-15 11:59 UTC
