### ISSUE TITLE
[FR] Relax requirements for "Installed" items

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#2045] opened 2021-09-08 17:55 UTC
**Problem**
Both Component and Assembly parts have to be Trackable to be installed in one another.
My usecase: tracking of computer parts inside computer assemblies. Every computer has: case, motherboard, hdd, etc.
I would like to create "Computer" part as assembly and all of its sub-parts as components and install them into "Computer" to know precisely where they are stored. Making them all trackable is over-complicate everything.

**Suggested solution**
Remove requirement for assembly to be trackable to enable install feature.
Remove requirement for components to be trackable to enable install feature. 
Change Location description of installed part from "Installed in Stock Item 639" to "Installed in "Part name"".

**Describe alternatives you've considered**
Relax only trackable requirement.

**Comment by matmair** [comment] 2021-09-08 18:39
Sounds like a simple general-purpose asset-management solution would be better suited for your use case.
I personally would not treat this with high importance but if it does not break anything else why not. @sintech would you be willing to implement this? Should be fairly easy.

What do you think @SchrodingersGat @eeintech ? yes 🚀, alternative solution 👍 or  no👎 ?

**Comment by eeintech** [comment] 2021-09-08 19:55
Here is how I interpret the idea: installing a number of "thing" into a number of "another thing" **without** specifically having a way to point which "thing" item goes to which "another thing" item.

I _think_ most of the logic is already present in the build **allocation** process, but this would have to be ported over to stock items. And maybe a global "stock item allocation" makes more sense, this global allocation could let the user execute allocation either from the "Stock" (to either stock items or build orders) view or "Build" view (from stock items).

For the stock side, those would be the new relationships:
1. install serialized `StockItem` into serialized `StockItem` (already exists)
2. install generic `StockItem` into serialized `StockItem` (example: 10 screws into a single, trackable case)
3. install generic `StockItem` into generic `StockItem` (example: 150 screws into 15 cases)

In the second case, the item being installed should have the option to split into:
- items being installed into serialized item
- leftover items from installation

Now adding to this, in the third case, the item receiving the items being installed also needs to have the option to split into:
- items in which first item is present/installed
- leftover items still missing first item to be installed

@SchrodingersGat probably has a better idea of the allocation logic and if can be re-used in its current state.

**Comment by SchrodingersGat** [comment] 2021-09-09 01:37
@sintech I think what you are proposing would quickly become very complicated. The current "install into" logic is implemented in a particular way so that the BOM / assembly relationship defines what sort of parts can be logically installed into other parts.

If *any* part could be installed into *any* other part, how do you actually select the parts in the software, when you have thousands of different parts available in your database? Just scrolling through and selecting the one you want could become very tedious.

The existing logic allows you to narrow that down, so that the user does not have to search through your entire database of parts.

This is why the BOM relationship exists. You say that an assembly should be made up of a certain subset of your available component parts. Some of these parts are "trackable" - i.e. you want these to be tracked when they are installed inside an assembly. Some are *not* trackable - e.g. screws? - and you don't want to track these for the lifecycle of the assembly.

Specifying the BOM and which parts you want tracked does take some time at the start of the process. However I feel strongly that the "garbage in, garbage out" adage applies here. To make the InvenTree system work well for your application, you need well curated data.

I think that relaxing the requirements here would turn into a bit of a mess. In our system we have ~1000 different parts, and a lot of these parts are extremely similar (but, importantly different). The BOM (and build order system) ensures that we know exactly which parts should go into which other parts, and the user cannot install *other* random parts without updating the BOM first.

Does this make sense? Have I interpreted your request accurately?

**Comment by sintech** [comment] 2021-09-09 07:26
Thank you guys for comments.
@SchrodingersGat I agree about requirement for component to be in assembly BOM to be installed.
But why both assembly and component have to be trackable? How this helps with mess avoidance?

You also mentioned tedious part selection process (if any part could be installed), how is this differ from adding a line to a BOM?

**Comment by eeintech** [comment] 2021-09-09 16:08
@sintech I guess I missed this part of your solution:

> Remove requirement for component to be a part of assembly BOM to be installed.

That I completely **disagree** with, and completely agree with @SchrodingersGat 

For the two first points:

> Remove requirement for assembly to be trackable to enable install feature.
> Remove requirement for components to be trackable to enable install feature.

I think there are fair request because this is basically how allocation currently works: there is no need to have the parts be "trackable" to allocate them into a build order. And the build order can create stock items that are not trackable too. So I don't see much difference in bypassing the build order and do the same at the stock level.

**Comment by sintech** [comment] 2021-09-09 16:25
@eeintech Yes, I admit that component must be a part of assembly BOM to be installed. I was a bit rash about it.
If all agree that "trackable" requirement could be removed I would like to try to implement it by myself including Location display fix.

**Comment by SchrodingersGat** [comment] 2022-03-19 11:50
@sintech I think that this requirement has been met now? Can I close this out? Please let me know if you think this has not actually been addressed.

**Comment by sintech** [comment] 2022-03-19 12:11
@SchrodingersGat, no, part still has to be trackable to appear in "Install Stock Item" "Part*" field. And stock item should have assigned serial number to appear in "Stock Item*" field. And container part has to be trackable too.
Looks like nothing has changed in 0.6.x related to this FR.
Please reopen.

**Comment by matmair** [comment] 2022-03-20 01:10
Just my 2-cents: If you want to track what parts are installed into what stock you want to track details about it -> so the trackable makes sense. Also, it ensures that there is only one part assigned to the stock item.

**Comment by SchrodingersGat** [comment] 2022-03-20 05:35
I agree with @matmair here - I'm not sure what a suitable alternative would look like.

**Comment by sintech** [comment] 2022-03-20 07:42
I described my usecase in the first post: tracking of extension boards inside computer case or any other modules inside mother enclosure.
As far as I have only one item of each kind of sub-module I don't see any reason to make them trackable. In other case when I will have for ex. two video cards of the same model it makes sense to make them trackable. But again if they are identical does it matter where is what.
So why limit this very useful feature to only trackable parts. Users will decide what approach is better for them.

**Comment by matmair** [comment] 2022-03-20 16:24
@sintech there are things happening in the business logic regarding if a part is trackable or not. So it matters that a part is marked trackable. If we rove that flag we will just have to make a new flag for that or hide a lot of parts in the selection -> the amount of work for the user is the same.

This feature only works if certain requirements are met. The limits are very intentional and I think no one will appreciate it if the system gets unreliable but the trackable flag is gone.
I am not sure if your use case makes sense for the system. Tracking single-item per model individual parts is better suited for an asset tracking system as there is a certain level of setup needed per part.

**Comment by SchrodingersGat** [comment] 2022-03-20 22:17
I am in agreement with @matmair here - I don't think the proposed change makes sense for InvenTree

**Comment by sintech** [comment] 2022-03-21 08:20
@matmair , I'm sorry but I don't get your point. Why system will become unreliable?
It was already discussed that BOM requirement for container part is closing all issues with inner part selection. Assembly requirement doesn't allow any other parts to become container.
What happened in last 6 months that you guys have changed your opinion?
I'm not asking you to develop this if you don't like it, just don't reject it. I will do a PR eventually.

**Comment by eeintech** [comment] 2022-03-21 14:55
Hello @sintech

I'm sorry for your frustration, @matmair and @SchrodingersGat have been pushing forward with a lot of new features recently and it's an incredible effort given they are doing this on their free time.
The problem is, many more users means many more requests for new features... which could grow a, right now stable, software into a monster if one keeps on adding more and more things without framing the project.
I _think_ I understood your original idea, which sounded reasonable at first, but I understand also the reasons not to implement it.

You best bet is to show them that this is feasible without adding monstrous complexity and making them uncomfortable with that new feature :smiley:

**Comment by matmair** [comment] 2022-03-24 22:55
> I'm not asking you to develop this if you don't like it, just don't reject it. I will do a PR eventually.

@sintech if you have a PR that works I see no reason to not look at it.

> @matmair , I'm sorry but I don't get your point. Why system will become unreliable? It was already discussed that BOM requirement for container part is closing all issues with inner part selection. Assembly requirement doesn't allow any other parts to become container. What happened in last 6 months that you guys have changed your opinion?

There are architectural challenges with your requests - you will see yourself, especially when starting to add unit tests. Maybe your fresh view will find ways I could not think of - I would be glad to be proven wrong.
There are a lot of use cases for InvenTree and everything that is there should generally keep working in exactly the current way.
Things like tracking need to be reliable. Without a clear flag that enforces specific details about a part on each save() operation there could be edge cases that result in a duplication of tracking codes. If that ever makes it to master/release we might stirrup a lot of installations irreparable.
The more I discover the userbase I am less willing to take risks on security and business logic / API endpoints. We could cause quite a lot of damage.



> The problem is, many more users means many more requests for new features...

And also that. Feature creep is real and causes performance problems left and right. There are installs with over 10.000 parts and a over a million stock tracking entries.

In closing: please feel free to speak out and add your view. In this case, I do not see the added value fitting the cost but that is neither final nor a set truth.

**Comment by SchrodingersGat** [comment] 2022-05-10 05:32
@sintech we've recently made some changes to how "installed items" work which may be sufficient for your requirements here? I'm closing out this issue for now, LMK if there are any further issues.

**Closed by SchrodingersGat** 2022-05-10 05:32 UTC
Labels: enhancement, question, part
