### ISSUE TITLE
[FR] Pre-fill required quantity to PO when adding items from sales order page

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3164] opened 2022-06-09 14:34 UTC
**Problem**
I am using the "Purchase stock" button on the Sales order page (really helpful feature, btw).
I have no items allocated or shipped (I have nothing on stock).
The suggested quantity to add to the PO is 1 - much less than the sales order requires.

**Suggested solution**
It would make sense if the suggested quantity were the quantity required - ie total required, minus allocated stock.

**Describe alternatives you've considered**
It's not a big deal to change manually, so this is what I've done.

**Comment by matmair** [comment] 2022-06-09 15:17
@miggland seems like a reasonable request. There was a similar FR already but I cannot find it right now.
If you implement this please take a look at #2253 . We are switching to an API driven approach for the user-interface so the solution should best extend the current endpoints with an extra parameter to control this. @SchrodingersGat is the expert for our ui stuff though.

**Comment by SchrodingersGat** [comment] 2022-06-09 21:34
@miggland this is definitely a worthwhile feature. FYI I recently merged this PR - https://github.com/inventree/InvenTree/issues/1996 - which changed the parts ordering wizard from using back-end forms to using the API formsets.

However, this PR resulted in a regression of the exact feature you want - i.e. the "quantity" field being automatically calculated. This was because the API was missing some information required to determine how many parts are required in total across all orders and allocations.

This problem needs to be solved in the "general" case, not just for sales orders. Whenever the "order parts" form is opened, it needs to be able to calculate (for each selected part) what the required ordering quantity is.

**Comment by miggland** [comment] 2022-06-10 09:37
@SchrodingersGat did this maybe cause the following "bug" as well? Going from a supplier part to the purchase orders tab, I would have assumed the relevant POs should be shown.. however, all of them are shown. Only one in the list below is relevant for this part or supplier.

The page I'm on is: `example.com/supplier-part/38/#`. The title "Supplier Part Orders" makes me think this should show a curated list :)

![image](https://user-images.githubusercontent.com/1314853/173036916-27112cab-4ca8-48c4-95c5-6bf2df9cbeca.png)

**Comment by SchrodingersGat** [comment] 2022-06-10 09:47
That looks like this bug - https://github.com/inventree/InvenTree/pull/3115

What version are you running? That bug should have been fixed in `0.7.1`

**Comment by miggland** [comment] 2022-06-10 09:50
It does look like it, so nevermind my comment. I haven't updated this week, I'm on 0.7.0

**Comment by SchrodingersGat** [comment] 2022-06-10 10:01
Gotta keep it fresh!

**Closed** 2022-07-25 03:00 UTC
Labels: enhancement, order, user interface, api
