### ISSUE TITLE
'str' object has no attribute 'removesuffix'

### ISSUE THREAD

**Issue by robbiesahn** [inventree/InvenTree#5773] opened 2023-10-22 14:51 UTC
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

after doing an update using the apt update everytime I try and make any changes to a part I get 'str' object has no attribute 'removesuffix'

### Steps to Reproduce

1. Make any changes to a stocked item
2. it will error out

### Relevant log output

```bash
Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
response = response.render()

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 105, in render
self.content = self.rendered_content

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
return template.render(context, self._request)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 170, in render
return self._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/library.py", line 192, in render
output = self.func(*resolved_args, **resolved_kwargs)

File "/opt/inventree/InvenTree/generic/states/tags.py", line 14, in status_label
state = {cls.tag(): cls for cls in inheritors(StatusCode)}.get(typ, None)

File "/opt/inventree/InvenTree/generic/states/tags.py", line 14, in <dictcomp>
state = {cls.tag(): cls for cls in inheritors(StatusCode)}.get(typ, None)

File "/opt/inventree/InvenTree/generic/states/states.py", line 108, in tag
ref_name = cls.__name__.removesuffix('Status')

AttributeError: 'str' object has no attribute 'removesuffix'
```

**Comment by matmair** [comment] 2023-10-22 15:00
@robbiesahn Please provide the version info of your install, we can not help you with this little information. It probably is a python version mismatch though

**Comment by wolflu05** [comment] 2023-10-22 18:00
@matmair It is, see the dependency paths.

Duplicate of 
- #5619
- #5393
- ...

**Comment by wolflu05** [comment] 2023-10-22 18:01
Duplicate of #5619

**Comment by robbiesahn** [comment] 2023-10-22 19:21
ok... so I have .12 installed on Ubuntu 20. I used the sh script to install the requirements for the app. How do I point the app the use the new version of python. I installed python 3.9. is there a specific command I need to run? and I'm sorry if this is mentioned  somewhere

**Comment by matmair** [comment] 2023-10-23 21:25
You need to create a new venv if you upgraded your Python version. This is necessary because venv's statically link to a specific Python version (that was the default for `python` when the venv was created by the script).

## Steps:
1. go to your install dir: `cd /opt/inventree`
2. remove the venv `rm env -r`
3. create a new venv `python3 -m venv env`
4. activate venv `source env/bin/activate`
5. install invoke `pip install invoke`

### If you have a git/bare metal install

6. run updates `invoke update`
7. exit venv `deactivate`

### If you run a normal package install

6. run updates `invoke update`
7. exit venv `deactivate`
8. restart service `service inventree restart`

### If you run the digital ocean marketplace droplet

6. install pgsql dependencies `pip install psycopg2-binary pgcli`
6. run updates `invoke update`
7. exit venv `deactivate`
8. restart service `service inventree restart`

**Closed** 2023-11-12 20:31 UTC
Labels: question, setup
