### ISSUE TITLE
[BUG] URLs are mangled in links

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3864] opened 2022-10-27 07:34 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

When entering a link to a supplier part, such as:
`https://www.axel-larsson.se/Exego.aspx?p_id=341&ArtNr=0804020E`
the link is changed to
`https://www.axel-larsson.se/Exego.aspx?p_id=341&amp;ArtNr=0804020E`

This makes the URL incorrect.

### Steps to Reproduce

1. Go to part -> Suppliers.
2. Add/edit part.
3. Add link looking like above
4. Check link after saving

### Expected behavior

The link clicked should be as entered, so that the expected page is reached.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.4
Django Version: 3.2.15
Commit Hash: ca1fbf9
Commit Date: 2022-10-20
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

### Relevant log output

```shell
No.
```

**Comment by matmair** [comment] 2022-10-27 21:39
@miggland thanks for the report. Seems to be related to sanitisation; I will have a look.

**Comment by matmair** [comment] 2022-10-28 00:20
@miggland have you verified this still is happening on the demo? I can not reproduce via API or with the steps.

**Comment by matmair** [comment] 2022-10-28 00:21
![grafik](https://user-images.githubusercontent.com/66015116/198421115-9536d5c6-b8c1-4ce1-9816-ba16f7dc9d75.png)

**Comment by SchrodingersGat** [comment] 2022-10-28 01:25
@miggland I am also having trouble replicating this one. Can you share some additional screenshots of the problem?

**Comment by miggland** [comment] 2022-10-28 07:03
No I can't reproduce it in the demo. I'm on the latest stable version myself, so I didn't go to the demo.

If you have changed something with the sanitation since 0.8.4, that could have solved the problem.

After pasting the given link under "Link" as in the screenshot from @matmair above, in my instance the result looks like this:
![image](https://user-images.githubusercontent.com/1314853/198524212-919abd36-2a92-40eb-a05d-643290ee90bb.png)

This still occurs, ie if I overwrite the link and submit again the problem still occurs.

**Comment by SchrodingersGat** [comment] 2022-10-28 07:24
@miggland ok I tried exactly what you have done, but on latest master, and cannot reproduce. I'm going to close this out, as completed. Next stable is imminent

**Closed by SchrodingersGat** 2022-10-28 07:24 UTC
Labels: bug

**Comment by miggland** [comment] 2022-11-17 15:13
There might be more issues with this - I can't see exactly why it happens though. Steps here, just in case anyone has any ideas:

1 . Enter data through API (The data here has been entered through the API originally (that was the case with the links as well, I think).
2 . After entering data, it appears as expected (" instead of &quot;")
![image](https://user-images.githubusercontent.com/1314853/202483488-e384412e-6e6b-4ab7-912d-7aeb765d57e1.png)
3. Edit screen in the GUI -> Submitted without changing anything
![image](https://user-images.githubusercontent.com/1314853/202483597-ed4a2a82-ec4c-418a-a806-ae0810f7fe86.png)
4. Now the above has changed, see the top row, right column
![image](https://user-images.githubusercontent.com/1314853/202483723-851fe263-0933-4bcc-8b4d-757da5ce0e1d.png)
