### ISSUE TITLE
Zebra plugin malfunction

### ISSUE THREAD

**Issue by anonkwe** [inventree/InvenTree#4516] opened 2023-03-22 13:42 UTC
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

don't know if we gotta specify something somewhere, but here is a 4inches x 8 inches label. on the left is where it's exported to pdf, on the right is when we use print to zebra printer. as if it was just staying in portrait or something. not sure. note that this module is vital for label printing through the paying mobile app.. some help would be so much appreciated.

![image](https://user-images.githubusercontent.com/61838766/226921978-d14d1473-343c-4b85-86af-0c44ad03c429.png)

here is label's html code:
{% extends "label/label_base.html" %}

{% load l10n %}
{% load barcode %}
{% block style %}

.qr {
position: relative;
float: right;

    {% localize off %}
    height: 80mm;
    width: 80mm;
    {% endlocalize %}
}
.logo2 {
    height: 130px;
    vertical-align: top;
	display:inline;
	margin-left:40px;

}	
.stock {
	float: left;
	display:inline;
    font-family: Arial, Helvetica, sans-serif;
	font-size: 130px;
	text-align: center;
	vertical-align: top;
	margin-left:40px;
    {% localize off %}
    {% endlocalize %}
	}
	.stock2 {
    font-family: Arial, Helvetica, sans-serif;
	font-size: 20px;
	margin: 0px;
	float: right;
	display: inline;

    {% localize off %}
    {% endlocalize %}
	
	}
.stock3 {
    font-family: Arial, Helvetica, sans-serif;
	font-size: 50px;
	float: right;
	margin: 0px;
	display:inline;
l
    {% localize off %}
    {% endlocalize %}
		
}
	
{% endblock %}
{% block content %}
<img class='qr' src='{% qrcode qr_data %}'>
<img class='logo2' src='http://192.168.0.246/static/img/premontex.jpg'></img><h1 class='stock' margin="0px">{{ item.batch }}   </h1>
<p class='stock2'>{{ part.name }}</p><br><h2 class='stock3'>QTE: {{ quantity }} PMP</h2>
{% endblock %}

here is zebra.py code from your plugin:

"""
Label printing plugin for InvenTree.
Supports direct printing of labels on label printers
"""
# translation
from django.utils.translation import ugettext_lazy as _

# InvenTree plugin libs
from plugin import InvenTreePlugin
from plugin.mixins import LabelPrintingMixin, SettingsMixin

# Zebra printer support
import zpl
import socket

from inventree_zebra.version import ZEBRA_PLUGIN_VERSION

class ZebraLabelPlugin(LabelPrintingMixin, SettingsMixin, InvenTreePlugin):

    AUTHOR = "Michael Buchmann"
    DESCRIPTION = "Label printing plugin for Zebra printers"
    VERSION = ZEBRA_PLUGIN_VERSION
    NAME = "Zebra"
    SLUG = "zebra"
    TITLE = "Zebra Label Printer"

    SETTINGS = {
        'CONNECTION': {
            'name': _('Printer Interface'),
            'description': _('Select local or network printer'),
            'choices': [('local','Local printer e.g. USB'),('network','Network printer with IP address')],
            'default': 'local',
        },
        'IP_ADDRESS': {
            'name': _('IP Address'),
            'description': _('IP address in case of network printer'),
            'default': '',
        },
        'PORT': {
            'name': _('Port'),
            'description': _('Network port in case of network printer'),
            'default': '9100',
        },
        'THRESHOLD': {
            'name': _('Threshold'),
            'description': _('Threshold for converting grayscale to BW'),
            'default': '200',
        },
        'LOCAL_IF': {
            'name': _('Local Device'),
            'description': _('Interface of local printer'),
            'default': '/dev/usb/lp0',
        },

    }

    def print_label(self, **kwargs):

        # Extract width (x) and height (y) information
        # width = kwargs['width']
        # height = kwargs['height']

        # Read settings
        IPAddress = self.get_setting('IP_ADDRESS')
        Connection = self.get_setting('CONNECTION')
        Interface = self.get_setting('LOCAL_IF')
        Port = self.get_setting('PORT')
        Threshold = int(self.get_setting('THRESHOLD'))
        label_image = kwargs['png_file']

        fn = lambda x : 255 if x > Threshold else 0
        label_image = label_image.convert('L').point(fn, mode='1')

        # Uncomment this if you want to have in intermetiate png file for debugging. You will find it in src/Inventree
        # label_image.save('label.png')

        #Convert image to Zebra zpl
		
        l = zpl.Label(102, 203, 8)
	  height=
        l.origin(0, 0)
        l.write_graphic(label_image, 203)
        l.endorigin()

        # Send the label to the printer
        if(Connection=='local'):
            try:
                printer=open(Interface,'w')
                printer.write(l.dumpZPL())
                printer.close()
            except:
                raise ConnectionError('Error connecting to local printer')
        elif(Connection=='network'):    
            try:
                mysocket = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
                mysocket.connect((IPAddress, int(Port)))
                data=l.dumpZPL()
                mysocket.send(data.encode())
                mysocket.close ()
            except:
                raise ConnectionError('Error connecting to network printer')
        else:
            print('Unknown Interface')

### Steps to Reproduce

1. print label
2. select zebra printer
3. comes out as portrait.

### Expected behaviour

should be printing the same as when we seclect print to pdf

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0 dev
Django Version: 3.2.18
Commit Hash: 4d8311682
Commit Date: 2023-03-20
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'Zebra', 'slug': 'zebra', 'version': '0.2'}]

**Comment by matmair** [comment] 2023-03-22 17:12
This seems to be regarding a plugin, please report this in that repo https://github.com/SergeoLacruz/inventree-zebra-plugin

**Comment by anonkwe** [comment] 2023-03-22 17:20
@SergeoLacruz do you think this is an issue that can be resolved somehow

**Comment by SergeoLacruz** [comment] 2023-03-22 17:46
Hi,
Your reel if 4inches wide and the labels are 8 inches high?
The plugin is made for reels that ate 50mm wide and tha label is 30mm high. You changed the sizes and this seems to 
work as I see on your picture. The problem is that the plugin does not rotate. An image.rotate(90) might do the trick. 
You can also add parameters for widht and height, compare it with the data from the api and rotate automatically. 
This would make the plugin more flexible.  I do not use portrait labels. So there was no need for it. I even do not have
portrait labels to test it. 

Michael

**Comment by anonkwe** [comment] 2023-03-22 18:00
@SergeoLacruz thank you very much for the reply, sorry if I seem a bit clueless, quite not a developer, i do networks.. where would suggest to write that function in your code and how? Once again, thank you and sorry for all the questions

**Comment by SergeoLacruz** [comment] 2023-03-22 18:35
If I find some time I will try to do it. The implementation is probably easy but I also need to test it carefully. Printing is always complicated. Will take some days.

**Comment by SchrodingersGat** [comment] 2023-03-22 22:52
I'll close this out as it pertains to a particular plugin

**Closed by SchrodingersGat** 2023-03-22 22:52 UTC
Labels: question, plugin

**Comment by anonkwe** [comment] 2023-03-23 03:07
ltns ? lollll

**Comment by anonkwe** [comment] 2023-03-23 03:10
just redid the label portrait style so yeah. i feel i get replies only when told to repost elsewhere. even if i got some limited knowledge I do feel like I flag some pertinent stuff ... anyways

**Comment by matmair** [comment] 2023-03-23 06:19
@anonkwe This is a free software project developed in the spare time of devs that have work, family and other obligations. We are happy to review PRs for the numerous requests you have filed in the last two weeks.

We are not getting payed for anything here and generating low-effort traffic on issues mainly takes away from the limited dev time. If you want snappy support, there are payed solutions like PartsBox or Odoo out there.
