### ISSUE TITLE
[BUG] Importing third paty Part data from admin panel fails

### ISSUE THREAD

**Issue by G-Pereira** [inventree/InvenTree#3341] opened 2022-07-16 17:54 UTC
**Describe the bug**
An error is thrown while importing Part data in the admin panel.

I've started by importing Part categories and Stock locations which went fine then when I import Part data it gives me the following error:
```python
Line number: 1 - Cannot call get_descendants on unsaved Part instances
28, 2015-10-20 21:21:54.571+00, 2015-10-20 21:21:54.571+00, Polar heart rate monitor, default/item_avatar.png, 1, (sem descrição), , 17, 6, , f, f, 0, 0, 0, 0

Traceback (most recent call last):
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/resources.py", line 644, in import_row
diff = self.get_diff_class()(self, original, new)
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/resources.py", line 204, in __init__
self.left = self._export_resource_fields(resource, instance)
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/resources.py", line 225, in _export_resource_fields
return [resource.export_field(f, instance) if instance else "" for f in resource.get_user_visible_fields()]
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/resources.py", line 225, in <listcomp>
return [resource.export_field(f, instance) if instance else "" for f in resource.get_user_visible_fields()]
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/resources.py", line 845, in export_field
return field.export(obj)
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/fields.py", line 122, in export
value = self.get_value(obj)
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/fields.py", line 98, in get_value
value = value()
File "/home/inventree/InvenTree/part/models.py", line 1403, in allocation_count
self.build_order_allocation_count(**kwargs),
File "/home/inventree/InvenTree/part/models.py", line 1327, in build_order_allocation_count
query = self.build_order_allocations(**kwargs).aggregate(
File "/home/inventree/InvenTree/part/models.py", line 1313, in build_order_allocations
variants = self.get_descendants(include_self=True)
File "/home/inventree/.local/lib/python3.9/site-packages/mptt/models.py", line 391, in _fn
raise ValueError(
ValueError: Cannot call get_descendants on unsaved Part instances
```

**Steps to Reproduce**

1. Go to the admin panel and import the following data under each data model:
  - Stock -> Stock locations
```
id,name,created,updated
6,O301,2015-10-20 20:54:17.501+00,2021-12-28 21:36:44.036767+00
```
  - Part -> Part Categories
```
"id","name","created","updated"
"17","Eletrónica","2015-10-21","2015-10-21 16:32:39.773+00"
```
  - Part -> Parts
```
id,created,updated,name,avatar,quantity,description,IPN,category,container_id,link,in_use,restricted,default_expiry,minimum_stock,base_cost,multiple
28,2015-10-20 21:21:54.571+00,2015-10-20 21:21:54.571+00,Polar heart rate monitor,default/item_avatar.png,1,(sem descrição),,17,6,,f,f,0,0,0,0
```

**Expected behavior**
The Parts would be imported successfully with the data provided

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
InvenTree-Version: 0.7.4
Django Version: 3.2.13
Commit Hash: f107aa0
Commit Date: 2022-06-23
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by G-Pereira** [comment] 2022-07-16 18:37
I added the following columns to the Parts CSV file but still does not work:
```
assembly,component,trackable,purchaseable,salable,active,virtual
0,1,0,1,0,1,0
```

**Comment by SchrodingersGat** [comment] 2022-07-16 22:55
@G-Pereira this looks to be a duplicate of https://github.com/inventree/InvenTree/issues/3234 

This issue has already been fixed (in the upcoming `0.8.0` release)

**Closed by SchrodingersGat** 2022-07-16 22:55 UTC
Labels: bug, question

**Comment by G-Pereira** [comment] 2022-07-16 23:14
I am testing against the latest tag of the docker image now and I am still getting errors, although it is a different one:
```
Line number: 1 - Part matching query does not exist.
28, 2015-10-20 21:21:54.571+00, 2015-10-20, 2015-10-20 21:21:54.571+00, Polar heart rate monitor, default/item_avatar.png, 1, (sem descrição), , 17, 6, , f, f, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1

Traceback (most recent call last):
File "/root/.local/lib/python3.9/site-packages/import_export/resources.py", line 668, in import_row
self.save_instance(instance, using_transactions, dry_run)
File "/root/.local/lib/python3.9/site-packages/import_export/resources.py", line 446, in save_instance
instance.save()
File "/home/inventree/InvenTree/part/models.py", line 404, in save
previous = Part.objects.get(pk=self.pk)
File "/root/.local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
raise self.model.DoesNotExist(
part.models.Part.DoesNotExist: Part matching query does not exist.
```

**Comment by G-Pereira** [comment] 2022-07-16 23:31
Found out that the issue was having a id column on the csv import file. On other models I imported IDs successfully buy on parts it doesn't seem to be possible

**Comment by SchrodingersGat** [comment] 2022-07-16 23:38
Yes if you have an "ID" column the import tool attempts to update existing records by matching the ID values.

**Comment by G-Pereira** [comment] 2022-07-16 23:43
Makes sense. I've got it all imported now! Amazing, thanks a lot for the support :)

**Comment by G-Pereira** [comment] 2022-07-17 00:29
@SchrodingersGat now that I've imported the data on the `latest` docker image tag is it safe to change it back to `stable` docker image tag?

**Comment by SchrodingersGat** [comment] 2022-07-17 06:21
@G-Pereira you can try but make sure you back up your data first! There are data migrations on master which have not been applied to stable, but honestly I'm not sure if they are breaking or not.
